table dim_distributors
	lineageTag: d0f821f6-5b0b-4260-aca7-8a7b213fac15

	column code
		dataType: string
		lineageTag: eee2d113-4ee6-44d9-8764-eba4ef7f4158
		summarizeBy: none
		sourceColumn: code

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 5eb4e46e-23fd-4195-861f-021d6d64f934
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column display_name
		dataType: string
		lineageTag: 886ed970-af25-495b-bfdf-a765e43c5887
		summarizeBy: none
		sourceColumn: display_name

		annotation SummarizationSetBy = Automatic

	column company_name
		dataType: string
		lineageTag: e30fe196-a094-4d25-bcdd-92f93e1f3040
		summarizeBy: none
		sourceColumn: company_name

		annotation SummarizationSetBy = Automatic

	column business_model
		dataType: string
		lineageTag: 871b3cb7-12f0-426c-82bb-3f9daf2883de
		summarizeBy: none
		sourceColumn: business_model

		annotation SummarizationSetBy = Automatic

	column role
		dataType: string
		lineageTag: 4ec9bd8e-45cd-4fbf-a04b-ac2d4ec6c502
		summarizeBy: none
		sourceColumn: role

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: e0c8c128-a787-4752-b762-95c03475f00c
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column id
		dataType: string
		lineageTag: da889b5e-8ba0-42b7-831c-30122d5aa4ac
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column tenant_id
		dataType: string
		lineageTag: 6c48ebf2-2ef1-484c-a794-04e605b4146c
		summarizeBy: none
		sourceColumn: tenant_id

		annotation SummarizationSetBy = Automatic

	column tenant
		dataType: string
		lineageTag: 7930ed2b-b0d8-44c4-a5f6-24ffc87e2523
		summarizeBy: none
		sourceColumn: tenant

		annotation SummarizationSetBy = Automatic

	column data_source
		dataType: string
		lineageTag: 43a0f86f-98db-4960-a38e-4efbd40a6224
		summarizeBy: none
		sourceColumn: data_source

		annotation SummarizationSetBy = Automatic

	partition dim_distributors-42b25e6e-be0a-4ed9-b6b4-d38e2559f21f = m
		mode: import
		queryGroup: Dim
		source =
				let
				    Fonte = Databricks.Catalogs(#"hostname", #"http_path_master_principal", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Fonte{[Name=#"ambiente_conexao",Kind="Database"]}[Data],
				    data_intelligence_prd_Schema = hive_metastore_Database{[Name="master_data_context",Kind="Schema"]}[Data],
				    dim_distributors_Table = data_intelligence_prd_Schema{[Name="dim_distributors",Kind="Table"]}[Data],
				    #"Linhas Filtradas" = Table.SelectRows(dim_distributors_Table, each ([business_model] = "B2B"))
				in
				    #"Linhas Filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

