table 'Medidas Produto'
	lineageTag: 8e6193b8-4925-48c9-9eee-122ad58e6e50

	measure CountRows_1_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 1,
			        'dim_access_control'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: b1d9bc6f-2af6-4eb3-941c-551aa400f529

	measure CountRows_1_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 1,
			        'dim_access_control'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 2784e963-120c-40cb-8cc0-4e6bbe9b7414

	measure CountRows_1_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 1,
			        'dim_access_control'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: e28c5a0f-714a-4350-8270-cb9788a41fcb

	measure CountRows_1_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 1,
			        'dim_access_control'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 3de6a7e0-97c2-497f-9a2f-76907ccb892c

	measure CountRows_1_5 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 1,
			        'dim_access_control'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: afa8fe1d-1df7-4d38-a068-f2e10bd22f39

	measure CountRows_1_6 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 1,
			        'dim_access_control'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 9c21a4ad-d482-45d5-bd86-ab5dd1132336

	measure CountRows_10_1 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 10,
			        'dim_access_control'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: fd3ab7e0-1a31-4541-96f6-cf3df26a89bc

	measure CountRows_10_2 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 10,
			        'dim_access_control'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 3fb1e0b9-05bb-4b3b-a031-f1543fd8f4de

	measure CountRows_10_3 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 10,
			        'dim_access_control'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 456dc223-68f9-4437-8f08-e36b9b4555ba

	measure CountRows_10_4 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 10,
			        'dim_access_control'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: cc45a9e6-2fc9-4555-89c1-f00be268948a

	measure CountRows_10_5 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 10,
			        'dim_access_control'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 46d06965-da05-4454-9d9d-3767559546f0

	measure CountRows_11_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 11,
			        'dim_access_control'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 29d56845-944c-412a-be06-0a3a5d1975ef

	measure CountRows_11_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 11,
			        'dim_access_control'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 2f85e967-dd75-4d0d-8653-602f1565154b

	measure CountRows_11_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 11,
			        'dim_access_control'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 8ed69e71-c7be-4679-aa2c-b2789c685751

	measure CountRows_11_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 11,
			        'dim_access_control'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 339451ec-5ad8-4e1a-a14d-53bf921a6092

	measure CountRows_11_5 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 11,
			        'dim_access_control'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: f5c934fa-6925-4ab5-b222-5eb36d1ca03d

	measure CountRows_12_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 12,
			        'dim_access_control'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 55087ab8-0251-40db-9ce2-c0777b2952b2

	measure CountRows_12_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 12,
			        'dim_access_control'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 2da1f2b2-54e4-4c64-9386-7ce8bedc36f2

	measure CountRows_2_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 2,
			        'dim_access_control'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 17c52d3d-0cfb-43cb-99be-0a3b8af47611

	measure CountRows_2_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 2,
			        'dim_access_control'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: c0774afe-1ce3-450d-8cef-603330031471

	measure CountRows_2_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 2,
			        'dim_access_control'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: a383eedf-6e9a-4751-a397-831774761211

	measure CountRows_2_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 2,
			        'dim_access_control'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: a8a7af73-4f0d-4116-8b18-a04be86cb8ed

	measure CountRows_2_5 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 2,
			        'dim_access_control'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 8a74348d-c871-475d-ba1c-464c0bf132c0

	measure CountRows_3_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 3,
			        'dim_access_control'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: eda71b9f-766d-4ff7-b406-3ca0dcb0ffdd

	measure CountRows_3_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 3,
			        'dim_access_control'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: d8fd388b-da6a-4172-b627-a4efa886e9e7

	measure CountRows_3_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 3,
			        'dim_access_control'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 5175bd3b-d618-40f1-8992-1dd78ee9b0ef

	measure CountRows_3_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 3,
			        'dim_access_control'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 6d70a6ad-702c-4dde-9fb3-bc5ccfa4b440

	measure CountRows_4_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 4,
			        'dim_access_control'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 2473ca33-8b78-433d-8179-6bddf72e7a8d

	measure CountRows_4_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 4,
			        'dim_access_control'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 5f4fb929-0692-4f93-9d96-704a57545a3a

	measure CountRows_4_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 4,
			        'dim_access_control'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: fbef3ce3-8c1f-431a-b978-47cc30130810

	measure CountRows_4_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 4,
			        'dim_access_control'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 47c031d3-cbac-4785-962e-6921eec65b8b

	measure CountRows_5_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 5,
			        'dim_access_control'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: ba8b3201-43ab-42d1-81e3-badb0c00e094

	measure CountRows_5_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 5,
			        'dim_access_control'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 4c470f7f-582f-4a9d-8eed-f5ade6348d04

	measure CountRows_5_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 5,
			        'dim_access_control'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 20007d8d-a0fc-4fb1-9419-f9226c8eb25b

	measure CountRows_5_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 5,
			        'dim_access_control'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 6f203401-14bd-4634-8da0-33beaae78ccf

	measure CountRows_5_5 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 5,
			        'dim_access_control'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: c64212e6-1828-4865-934b-433bcbf2838a

	measure CountRows_6_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 6,
			        'dim_access_control'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: a43b786d-e6ee-4aec-8e25-1a69d2d746a0

	measure CountRows_6_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 6,
			        'dim_access_control'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: c8247035-dae5-4ea6-9f66-006adf7609a7

	measure CountRows_6_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 6,
			        'dim_access_control'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 7c208ab7-0fc4-4b62-9115-c65e96854c13

	measure CountRows_6_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 6,
			        'dim_access_control'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 5b8b0551-38ea-41fc-bd82-6659228431b0

	measure CountRows_6_5 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 6,
			        'dim_access_control'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 9259d6a3-2fea-4363-91e1-77738be95297

	measure CountRows_7_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 7,
			        'dim_access_control'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 770b9d9a-f797-4aa0-8911-d7d832d517e0

	measure CountRows_7_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 7,
			        'dim_access_control'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 79f2f944-97a2-449b-bdbb-a1e40fe468a0

	measure CountRows_7_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 7,
			        'dim_access_control'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: c280d38e-5db0-413e-b96d-29fb53353d2d

	measure CountRows_7_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 7,
			        'dim_access_control'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: b1d43356-5413-4906-acdd-f7717a67c5df

	measure CountRows_7_5 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 7,
			        'dim_access_control'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: c08891d2-5c85-40d2-8d43-64762bed35b3

	measure CountRows_8_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 8,
			        'dim_access_control'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 7879ff82-0237-4b23-9d08-2fb8968f207b

	measure CountRows_8_2 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 8,
			        'dim_access_control'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 48325e43-626b-49d4-b106-7792970677c3

	measure CountRows_8_3 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 8,
			        'dim_access_control'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: c99d63e5-e873-4fa4-b46a-462d86cb199e

	measure CountRows_8_4 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 8,
			        'dim_access_control'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 4a050fd5-70d2-4e6b-85dd-af397e17d18a

	measure CountRows_8_5 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 8,
			        'dim_access_control'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 85141550-c5e2-4d8f-ae13-0fd4cd4c2233

	measure CountRows_8_6 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 8,
			        'dim_access_control'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 9a957d0b-2838-4023-b90b-7b3f5d07969e

	measure CountRows_8_7 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 8,
			        'dim_access_control'[id_dashboard] = 7) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 0311d7a5-9e6c-42d4-816f-0e5a7584e4e6

	measure CountRows_8_8 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 8,
			        'dim_access_control'[id_dashboard] = 8) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 427360c4-b9cc-4944-936c-5207cdbc1a5e

	measure CountRows_9_1 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 9,
			        'dim_access_control'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 9e68ebae-f55f-4fc4-9e21-818fbc483b2b

	measure CountRows_9_2 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 9,
			        'dim_access_control'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 9da93aa7-5673-45b5-80ea-806b431f2978

	measure CountRows_9_3 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 9,
			        'dim_access_control'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: aeb5b369-c909-4a07-9602-4154c86a83f0

	measure CountRows_9_4 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 9,
			        'dim_access_control'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 729c2a2a-13d2-4102-b11e-72e01fbcbfa3

	measure CountRows_9_5 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 9,
			        'dim_access_control'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 68121eee-b88c-458d-b8fe-2f039bf6745e

	measure CountRows_9_6 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 9,
			        'dim_access_control'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 38d3e344-7c5d-4493-a291-de7b838ddae4

	measure CountRows_9_7 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 9,
			        'dim_access_control'[id_dashboard] = 7) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 20e9c2df-4f44-4060-a708-a635032d1be0

	measure CountRows_2_6 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 2,
			        'dim_access_control'[id_dashboard] = 6
			        ) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 9e66df09-b8e8-49f1-bbd6-bc95bcd52b53

	measure CountRows_3_5 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 3,
			        'dim_access_control'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: e0ab3ca4-9e5f-44b4-8da6-8674317a122f

	measure CountRows_3_6 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 3,
			        'dim_access_control'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 32d32fd5-9d0c-45c5-a81d-70a1f48da274

	measure CountRows_4_5 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 4,
			        'dim_access_control'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 815807f9-1881-4e78-8df8-ae565bbf600d

	measure CountRows_4_6 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 4,
			        'dim_access_control'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 9871cbb1-0ebf-4391-b656-c68efd736efe

	measure CountRows_5_6 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 5,
			        'dim_access_control'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 25e82d7d-c749-4cae-8022-e43c86298b5e

	measure CountRows_6_6 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 6,
			        'dim_access_control'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 5ba9e379-89c3-468b-a91c-f6f4d586bd77

	measure CountRows_7_6 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 7,
			        'dim_access_control'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: ca515e02-faf0-4269-a93a-00b0edc99dae

	measure CountRows_11_6 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 11,
			        'dim_access_control'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 0dc37c49-401a-4c1d-92c6-d5c9cf5ad500

	measure CountRows_10_6 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 10,
			        'dim_access_control'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: e19d2180-55fb-45c4-851b-132500613d31

	measure CountRows_8_9 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 8,
			        'dim_access_control'[id_dashboard] = 9) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: a29029a7-9ee7-4a54-b76a-804baaf62b04

	measure CountRows_9_8 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 9,
			        'dim_access_control'[id_dashboard] = 8) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 3e222697-3a05-4c35-b306-2f365663ad08

	measure CountRows_9_9 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 9,
			        'dim_access_control'[id_dashboard] = 9) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 81b2d640-c876-47ec-a917-109e1a7d6239

	measure CountRows_10_7 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 10,
			        'dim_access_control'[id_dashboard] = 7) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: cbc8f64b-ac70-441a-9c27-ea66a23cc7e3

	measure CountRows_10_8 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 10,
			        'dim_access_control'[id_dashboard] = 8) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 13f0752f-71be-4a22-9285-7d06edd4bbb6

	measure CountRows_10_9 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 10,
			        'dim_access_control'[id_dashboard] = 9) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 186ad65d-0b8d-4e61-b409-2229b19a77ce

	measure CountRows_12_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 12,
			        'dim_access_control'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		displayFolder: countrows_access_control
		lineageTag: 9e213f75-f578-4640-bd61-6a1467589815

	measure CountRows_13_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 13,
			        'dim_access_control'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 73d7885e-1c91-467d-85f1-9e2635fec0c2

	measure CountRows_14_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 14,
			        'dim_access_control'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 7b467183-d2f0-4204-8b4e-7c784487b88b

	measure CountRows_15_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 15,
			        'dim_access_control'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: d7af721f-dd8c-4499-ab41-bed6b48a499b

	measure CountRows_13_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 13,
			        'dim_access_control'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 5a332bf6-3e18-42fb-bbd4-d7c33ae698aa

	measure CountRows_14_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 14,
			        'dim_access_control'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 6c6ac4ca-8595-40c8-bb1e-2fabc177789b

	measure CountRows_15_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 15,
			        'dim_access_control'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: c4cd9290-c5b6-4625-b41d-a132ceb2d020

	measure CountRows_13_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 13,
			        'dim_access_control'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: c69692c2-5a24-4f5b-a14a-0b3eceff928a

	measure CountRows_14_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 14,
			        'dim_access_control'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: be8fcf44-f96a-453f-a90a-269dbf4eb62a

	measure CountRows_15_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 15,
			        'dim_access_control'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: eee9fa53-2aea-4648-9e8d-0157db294b20

	measure CountRows_13_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 13,
			        'dim_access_control'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 51d7b75e-8c57-4128-96e7-5a60c1a31bb1

	measure CountRows_14_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 14,
			        'dim_access_control'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 72e8f47e-8cd6-4ef3-91e9-9805f92b9ec7

	measure CountRows_15_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 15,
			        'dim_access_control'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 81ce23d3-9d1b-4d73-a65b-132450d81873

	measure CountRows_13_5 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 13,
			        'dim_access_control'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: e1568c17-f87d-4519-ae95-5396b5911b8c

	measure CountRows_14_5 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 14,
			        'dim_access_control'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: ad6241a2-899c-4e4b-9bb9-7dd20827145f

	measure CountRows_15_5 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 15,
			        'dim_access_control'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 1ab9d375-4d0c-465c-a056-09f5d644be8c

	measure CountRows_13_7 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 13,
			        'dim_access_control'[id_dashboard] = 7) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 93e75910-8059-4d4f-8dbe-00df327170e3

	measure CountRows_14_6 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 14,
			        'dim_access_control'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 738912bb-9fd5-4c36-9b81-e2f20a44d205

	measure CountRows_15_6 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 15,
			        'dim_access_control'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 6dd6e861-2915-4beb-b286-42fcc80c2dc3

	measure CountRows_13_6 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 13,
			        'dim_access_control'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 6634aeba-fc62-4ec5-a6e9-c39e19a67018

	measure CountRows_14_7 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 14,
			        'dim_access_control'[id_dashboard] = 7) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: e241ccb6-ab21-45a7-89e0-3575a6ab1d2c

	measure CountRows_15_7 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 15,
			        'dim_access_control'[id_dashboard] = 7) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 776105ce-373c-4c6a-bf33-94bb8b5ec992

	measure CountRows_13_8 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 13,
			        'dim_access_control'[id_dashboard] = 8) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 00988bce-2841-4143-b5c5-397113ab7ea3

	measure CountRows_14_8 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 14,
			        'dim_access_control'[id_dashboard] = 8) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 20234b0e-4e35-46db-8695-96c91d8fde1f

	measure CountRows_15_8 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 15,
			        'dim_access_control'[id_dashboard] = 8) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: d1a6a483-f6d3-43d4-b576-836d8a128c93

	measure CountRows_13_9 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 13,
			        'dim_access_control'[id_dashboard] = 9) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 651f934f-ad79-4305-8dbf-38eca59ff29f

	measure CountRows_14_9 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 14,
			        'dim_access_control'[id_dashboard] = 9) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: f4435978-5300-46ab-98d6-d7a481b6432a

	measure CountRows_15_9 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 15,
			        'dim_access_control'[id_dashboard] = 9) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_access_control
		lineageTag: 7c1ea892-37c1-4862-a7a3-9d27da4cfc6e

	measure dash_name_1_1_1 =
			CALCULATE (
			    IF ( [CountRows_url_1_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 93c2a2f7-6492-4de0-bc6f-92fdde1deb8d

	measure dash_name_1_1_2 =
			CALCULATE (
			    IF ( [CountRows_url_1_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: dash_name
		lineageTag: 66cb4b32-8f55-4dd3-baff-dacb531ab6ec

	measure dash_name_1_1_3 =
			CALCULATE (
			    IF ( [CountRows_url_1_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: dash_name
		lineageTag: 8a4a968e-4825-45b9-84d5-ae2f91e221a9

	measure dash_name_1_1_4 =
			CALCULATE (
			    IF ( [CountRows_url_1_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: dash_name
		lineageTag: 6d59f207-6aff-4b23-9305-d48f33b1f5c7

	measure dash_name_1_1_5 =
			CALCULATE (
			    IF ( [CountRows_url_1_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: dash_name
		lineageTag: f1e3b3e5-60c1-4f02-ac04-606ec3788a7e

	measure dash_name_1_2_1 =
			CALCULATE (
			    IF ( [CountRows_url_1_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 992e9d4a-d833-44fb-a2ab-b0d6db0f7ebb

	measure dash_name_1_2_2 =
			CALCULATE (
			    IF ( [CountRows_url_1_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: dash_name
		lineageTag: 0090f3c8-aab5-4569-920e-ff039649674c

	measure dash_name_1_2_3 =
			CALCULATE (
			    IF ( [CountRows_url_1_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: dash_name
		lineageTag: 33d48eca-de22-4ab3-abf4-1983da9a6a2c

	measure dash_name_1_3_1 =
			CALCULATE (
			    IF ( [CountRows_url_1_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: fe66dd5f-b37e-428f-96e7-67db8d2e1ad3

	measure dash_name_1_4_1 =
			CALCULATE (
			    IF ( [CountRows_url_1_4] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: db997e1c-deda-4624-8467-ba0957f73f85

	measure dash_name_1_4_2 =
			CALCULATE (
			    IF ( [CountRows_url_1_4] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: dash_name
		lineageTag: a7082eba-ce9c-464c-8f61-52dd84695bb1

	measure dash_name_1_4_3 =
			CALCULATE (
			    IF ( [CountRows_url_1_4] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: dash_name
		lineageTag: 1e01f4f8-b0be-4db3-b406-a79ddd5da8b4

	measure dash_name_1_4_4 =
			CALCULATE (
			    IF ( [CountRows_url_1_4] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: dash_name
		lineageTag: 28ab3162-efc8-4577-9786-bff0b881ffa9

	measure dash_name_1_4_5 =
			CALCULATE (
			    IF ( [CountRows_url_1_4] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: dash_name
		lineageTag: e01c609d-8c46-4e50-a937-0de9771eac80

	measure dash_name_1_4_6 =
			CALCULATE (
			    IF ( [CountRows_url_1_4] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: dash_name
		lineageTag: 31ff510c-3769-45ee-a236-69640e070796

	measure dash_name_1_4_7 =
			CALCULATE (
			    IF ( [CountRows_url_1_4] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 7
			)
		displayFolder: dash_name
		lineageTag: eaeece15-3cdf-449b-88f7-58fccb3c54c5

	measure dash_name_1_5_1 =
			CALCULATE (
			    IF ( [CountRows_url_1_5] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: c284e7c0-9ebd-40f8-9fd4-4f634398aeed

	measure dash_name_1_6_1 =
			CALCULATE (
			    IF ( [CountRows_url_1_6] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 5d4ca42e-7438-400a-aca1-8201e9bfe232

	measure dash_name_1_6_2 =
			CALCULATE (
			    IF ( [CountRows_url_1_6] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: dash_name
		lineageTag: f8237c47-117a-4bfd-b78c-704e33e31e55

	measure dash_name_1_6_3 =
			CALCULATE (
			    IF ( [CountRows_url_1_6] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: dash_name
		lineageTag: 0c43da80-a050-4268-ad09-1f66e3b9e1b6

	measure dash_name_10_1_1 =
			CALCULATE (
			    IF ( [CountRows_url_10_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 87d74251-df68-4c0e-8aa2-dfd454ec9cad

	measure dash_name_10_2_1 =
			CALCULATE (
			    IF ( [CountRows_url_10_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: b5811754-4c61-443d-956f-f524e16cc1e4

	measure dash_name_10_3_1 =
			CALCULATE (
			    IF ( [CountRows_url_10_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 5400fa70-1268-4eb3-8ebd-b32016d64ee8

	measure dash_name_10_4_1 =
			CALCULATE (
			    IF ( [CountRows_url_10_4] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 4d1e2651-6c8b-4626-80cd-1ba6a571c67a

	measure dash_name_10_5_1 =
			CALCULATE (
			    IF ( [CountRows_url_10_5] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 0ecfb33d-9a39-4403-a4be-475f6fb5522c

	measure dash_name_11_1_1 =
			CALCULATE (
			    IF ( [CountRows_url_11_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 1c8599d5-80de-4e66-ac27-203294a3e832

	measure dash_name_11_2_1 =
			CALCULATE (
			    IF ( [CountRows_url_11_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 9ef368ad-8837-4601-a7eb-90f4772dee5f

	measure dash_name_11_3_1 =
			CALCULATE (
			    IF ( [CountRows_url_11_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: cb1b5162-ce1d-4da4-916a-ba21fd405d66

	measure dash_name_11_4_1 =
			CALCULATE (
			    IF ( [CountRows_url_11_4] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 6be462d0-ef1e-437a-9ec1-9baf29f5aa27

	measure dash_name_11_5_1 =
			CALCULATE (
			    IF ( [CountRows_url_11_5] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: c5910d70-2a40-46a7-8d31-d3938180a0a7

	measure dash_name_11_5_2 =
			CALCULATE (
			    IF ( [CountRows_url_11_5] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: dash_name
		lineageTag: e302c824-9848-44ac-b7d3-6b89854f703f

	measure dash_name_12_1_1 =
			CALCULATE (
			    IF ( [CountRows_url_12_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 361500d6-62cb-44cd-9194-2c8c34524810

	measure dash_name_12_2_1 =
			CALCULATE (
			    IF ( [CountRows_url_12_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: c735fe80-bd4d-4ea0-8537-2d98e789d865

	measure dash_name_12_2_10 =
			CALCULATE (
			    IF ( [CountRows_url_12_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 10
			)
		displayFolder: dash_name
		lineageTag: b1550fa7-20df-4f9e-9467-02fdf3d12da7

	measure dash_name_12_2_11 =
			CALCULATE (
			    IF ( [CountRows_url_12_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 11
			)
		displayFolder: dash_name
		lineageTag: bc78e5a3-eb08-43a4-8430-701bb60e7916

	measure dash_name_12_2_12 =
			CALCULATE (
			    IF ( [CountRows_url_12_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 12
			)
		displayFolder: dash_name
		lineageTag: cb3939a2-9966-4383-9b10-9237d94282ed

	measure dash_name_12_2_13 =
			CALCULATE (
			    IF ( [CountRows_url_12_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 13
			)
		displayFolder: dash_name
		lineageTag: 4ad3dc5a-8104-4f07-8179-214058e6ffeb

	measure dash_name_12_2_14 =
			CALCULATE (
			    IF ( [CountRows_url_12_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 14
			)
		displayFolder: dash_name
		lineageTag: 9972fb5a-6de2-4d9a-bcdf-99593ac772c8

	measure dash_name_12_2_15 =
			CALCULATE (
			    IF ( [CountRows_url_12_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 15
			)
		displayFolder: dash_name
		lineageTag: 8682fb4c-713d-48bd-9062-1c6252ae5cb8

	measure dash_name_12_2_16 =
			CALCULATE (
			    IF ( [CountRows_url_12_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 16
			)
		displayFolder: dash_name
		lineageTag: 27d8dddb-298c-472a-a9d8-5cdf9a86d611

	measure dash_name_12_2_17 =
			CALCULATE (
			    IF ( [CountRows_url_12_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 17
			)
		displayFolder: dash_name
		lineageTag: ef5b8fde-5cfe-4fde-8774-f4be00cc3926

	measure dash_name_12_2_18 =
			CALCULATE (
			    IF ( [CountRows_url_12_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 18
			)
		displayFolder: dash_name
		lineageTag: 648ba23e-69cf-4a61-a881-6eb7d17ba25a

	measure dash_name_12_2_2 =
			CALCULATE (
			    IF ( [CountRows_url_12_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: dash_name
		lineageTag: 7582c554-1710-497e-9a57-87d654f45061

	measure dash_name_12_2_3 =
			CALCULATE (
			    IF ( [CountRows_url_12_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: dash_name
		lineageTag: 942b5891-fa46-4a7e-814b-dc9fe0f80962

	measure dash_name_12_2_4 =
			CALCULATE (
			    IF ( [CountRows_url_12_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: dash_name
		lineageTag: 5abd6546-01cf-4063-894c-fd6246534d22

	measure dash_name_12_2_5 =
			CALCULATE (
			    IF ( [CountRows_url_12_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: dash_name
		lineageTag: 73d868eb-91ea-4d50-a4d8-336f931fabcd

	measure dash_name_12_2_6 =
			CALCULATE (
			    IF ( [CountRows_url_12_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: dash_name
		lineageTag: 0b416613-f7e1-46b1-82e8-95ece6df43b5

	measure dash_name_12_2_7 =
			CALCULATE (
			    IF ( [CountRows_url_12_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 7
			)
		displayFolder: dash_name
		lineageTag: db4822f1-f306-4690-9618-4a75746b829b

	measure dash_name_12_2_8 =
			CALCULATE (
			    IF ( [CountRows_url_12_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 8
			)
		displayFolder: dash_name
		lineageTag: 87af67ff-d155-4405-8220-18627c5ece57

	measure dash_name_12_2_9 =
			CALCULATE (
			    IF ( [CountRows_url_12_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 9
			)
		displayFolder: dash_name
		lineageTag: 72afe5d0-123b-4b4e-9626-295bb6207a0f

	measure dash_name_2_1_1 =
			CALCULATE (
			    IF ( [CountRows_url_2_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 58824c2d-aaac-4c01-9bd0-6c7f403caee4

	measure dash_name_2_1_2 =
			CALCULATE (
			    IF ( [CountRows_url_2_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: dash_name
		lineageTag: e8f734de-aa36-483c-a4ee-f22dea9289d2

	measure dash_name_2_2_1 =
			CALCULATE (
			    IF ( [CountRows_url_2_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 753c448f-1bb6-4e22-b2f5-b0fd2a39ee46

	measure dash_name_2_3_1 =
			CALCULATE (
			    IF ( [CountRows_url_2_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 50440958-08b5-44f7-be4f-841712a33026

	measure dash_name_2_4_1 =
			CALCULATE (
			    IF ( [CountRows_url_2_4] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 71904904-4834-49ef-b302-ee85322d557e

	measure dash_name_2_5_1 =
			CALCULATE (
			    IF ( [CountRows_url_2_5] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: fabe6036-7034-4032-a252-0ea33bed0161

	measure dash_name_3_1_1 =
			CALCULATE (
			    IF ( [CountRows_url_3_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: ac72ff0d-699d-48a3-a05c-be441bc61a6e

	measure dash_name_3_2_1 =
			CALCULATE (
			    IF ( [CountRows_url_3_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 71bbeb25-b4a5-409f-9962-323e1bcd6409

	measure dash_name_3_3_1 =
			CALCULATE (
			    IF ( [CountRows_url_3_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 3640ccdf-c859-450d-b2f9-8913fb6b26c1

	measure dash_name_3_4_1 =
			CALCULATE (
			    IF ( [CountRows_url_3_4] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 3ccbe9bb-cfe8-4bd3-a19e-5f46094fe5a3

	measure dash_name_4_1_1 =
			CALCULATE (
			    IF ( [CountRows_url_4_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 341f3052-6b15-4c03-bdc0-c5c6b954d658

	measure dash_name_4_2_1 =
			CALCULATE (
			    IF ( [CountRows_url_4_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 5e68e764-8b81-4627-bcd2-0ef4ec5658f0

	measure dash_name_4_3_1 =
			CALCULATE (
			    IF ( [CountRows_url_4_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: af3a76a1-ba43-4616-aab9-0a2c092256c9

	measure dash_name_4_4_1 =
			CALCULATE (
			    IF ( [CountRows_url_4_4] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 0f1c64b7-f218-404d-b8f1-cd59dc57ec0f

	measure dash_name_5_1_1 =
			CALCULATE (
			    IF ( [CountRows_url_5_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 0427f2c7-7e22-440e-a8a9-61098eb119bd

	measure dash_name_5_1_2 =
			CALCULATE (
			    IF ( [CountRows_url_5_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: dash_name
		lineageTag: 0fd5774f-4115-4573-9906-099cb2c5ad7e

	measure dash_name_5_2_1 =
			CALCULATE (
			    IF ( [CountRows_url_5_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 94b0fb6f-53cc-494a-bdb7-4a803977c082

	measure dash_name_5_2_2 =
			CALCULATE (
			    IF ( [CountRows_url_5_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: dash_name
		lineageTag: c033e482-010b-46a2-955c-b2959c8ae869

	measure dash_name_5_3_1 =
			CALCULATE (
			    IF ( [CountRows_url_5_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: d7e12d17-7ba1-4958-8bd0-3bad5f905d82

	measure dash_name_5_4_1 =
			CALCULATE (
			    IF ( [CountRows_url_5_4] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 17177152-ae3f-4509-8e43-d2ab6d472548

	measure dash_name_5_5_1 =
			CALCULATE (
			    IF ( [CountRows_url_5_5] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 23b55ab8-de44-4736-bc6f-ed6751c27cc2

	measure dash_name_6_1_1 =
			CALCULATE (
			    IF ( [CountRows_url_6_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: a761d964-5f76-4c19-bcd8-6e010e02babe

	measure dash_name_6_1_2 =
			CALCULATE (
			    IF ( [CountRows_url_6_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: dash_name
		lineageTag: 2702b60a-211b-4fe6-92e2-7d7349ca5d2c

	measure dash_name_6_1_3 =
			CALCULATE (
			    IF ( [CountRows_url_6_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: dash_name
		lineageTag: ead96819-d8a4-4410-bedf-ef38a3cc00d1

	measure dash_name_6_1_4 =
			CALCULATE (
			    IF ( [CountRows_url_6_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: dash_name
		lineageTag: ab995cf1-45aa-4d48-a096-da1d23fd298c

	measure dash_name_6_1_5 =
			CALCULATE (
			    IF ( [CountRows_url_6_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: dash_name
		lineageTag: 50b7ef53-5755-4706-9a35-b4492b349db2

	measure dash_name_6_1_6 =
			CALCULATE (
			    IF ( [CountRows_url_6_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: dash_name
		lineageTag: 8e49c01c-beb9-4ba0-99c8-063add65eecc

	measure dash_name_6_1_7 =
			CALCULATE (
			    IF ( [CountRows_url_6_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 7
			)
		displayFolder: dash_name
		lineageTag: 09e17f27-a644-4981-bac8-833555502542

	measure dash_name_6_1_8 =
			CALCULATE (
			    IF ( [CountRows_url_6_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 8
			)
		displayFolder: dash_name
		lineageTag: 6aff4381-9df3-4a3e-8aef-e0812ac9c062

	measure dash_name_6_2_1 =
			CALCULATE (
			    IF ( [CountRows_url_6_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: dde0bd8a-c6d5-473e-a6a2-13ba8e3ce11d

	measure dash_name_6_2_2 =
			CALCULATE (
			    IF ( [CountRows_url_6_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: dash_name
		lineageTag: cec4384a-c272-47ca-b2cc-d2060daeb875

	measure dash_name_6_2_3 =
			CALCULATE (
			    IF ( [CountRows_url_6_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: dash_name
		lineageTag: 8e452896-7030-4a00-9b8d-dc0161b55173

	measure dash_name_6_2_4 =
			CALCULATE (
			    IF ( [CountRows_url_6_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: dash_name
		lineageTag: 8b2c6b12-30fe-4396-af88-30b657a1d921

	measure dash_name_6_2_5 =
			CALCULATE (
			    IF ( [CountRows_url_6_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: dash_name
		lineageTag: 76d73dc9-1699-4008-bd9d-4d491a54bacd

	measure dash_name_6_2_6 =
			CALCULATE (
			    IF ( [CountRows_url_6_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: dash_name
		lineageTag: 2034e5cf-4162-422b-9175-891923f9f5c7

	measure dash_name_6_2_7 =
			CALCULATE (
			    IF ( [CountRows_url_6_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 7
			)
		displayFolder: dash_name
		lineageTag: 4e86570f-5e7c-458c-b228-2a83e1659875

	measure dash_name_6_2_8 =
			CALCULATE (
			    IF ( [CountRows_url_6_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 8
			)
		displayFolder: dash_name
		lineageTag: 1d5b7b41-48d9-41b0-acad-ab8a1b6af220

	measure dash_name_6_3_1 =
			CALCULATE (
			    IF ( [CountRows_url_6_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: c05d9353-e2db-4954-ab41-8c4ee3f15e08

	measure dash_name_6_3_2 =
			CALCULATE (
			    IF ( [CountRows_url_6_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: dash_name
		lineageTag: 56875c31-b0b1-42e3-a2d1-d9f961c86484

	measure dash_name_6_3_3 =
			CALCULATE (
			    IF ( [CountRows_url_6_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: dash_name
		lineageTag: 2f9e8570-f3df-4be8-9e5b-e49e7e63d538

	measure dash_name_6_3_4 =
			CALCULATE (
			    IF ( [CountRows_url_6_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: dash_name
		lineageTag: 11d46810-08ac-44b0-a276-08d45c91414a

	measure dash_name_6_3_5 =
			CALCULATE (
			    IF ( [CountRows_url_6_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: dash_name
		lineageTag: ec379e5b-c025-4049-a0cf-7a2a244eeffa

	measure dash_name_6_4_1 =
			CALCULATE (
			    IF ( [CountRows_url_6_4] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: aa2dc00c-b8e1-46c3-8773-9e9eca894a4b

	measure dash_name_6_5_1 =
			CALCULATE (
			    IF ( [CountRows_url_6_5] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: c72cb824-0b5a-4537-9bab-4748c644be59

	measure dash_name_7_1_1 =
			CALCULATE (
			    IF ( [CountRows_url_7_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 5117cde9-252e-4e3c-84e3-c36043f48992

	measure dash_name_7_1_2 =
			CALCULATE (
			    IF ( [CountRows_url_7_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: dash_name
		lineageTag: eee5b8a2-5a8f-443b-81bd-7decf07bc1b8

	measure dash_name_7_1_3 =
			CALCULATE (
			    IF ( [CountRows_url_7_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: dash_name
		lineageTag: 528c520b-be6f-4e71-b703-f051e00e6ca1

	measure dash_name_7_1_4 =
			CALCULATE (
			    IF ( [CountRows_url_7_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: dash_name
		lineageTag: 4708ad73-cef8-4cc2-a88f-e8480ed80132

	measure dash_name_7_1_5 =
			CALCULATE (
			    IF ( [CountRows_url_7_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: dash_name
		lineageTag: eb35a828-9b34-42f7-9181-ff6c56203bd2

	measure dash_name_7_1_6 =
			CALCULATE (
			    IF ( [CountRows_url_7_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: dash_name
		lineageTag: f30920b9-f9d9-4311-8e2c-397b0d9a2dd1

	measure dash_name_7_1_7 =
			CALCULATE (
			    IF ( [CountRows_url_7_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 7
			)
		displayFolder: dash_name
		lineageTag: 688cc70e-4fcc-4bbb-aebf-48e2f414223e

	measure dash_name_7_1_8 =
			CALCULATE (
			    IF ( [CountRows_url_7_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 8
			)
		displayFolder: dash_name
		lineageTag: f4530b88-3d48-4bf1-afa5-a9e0d060c92e

	measure dash_name_7_2_1 =
			CALCULATE (
			    IF ( [CountRows_url_7_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: ebf91fb6-9a63-48c5-a8f7-c2b2bcf4685c

	measure dash_name_7_2_2 =
			CALCULATE (
			    IF ( [CountRows_url_7_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: dash_name
		lineageTag: 4c3a3ae5-ba5c-478a-bcd0-dcc5227a952c

	measure dash_name_7_2_3 =
			CALCULATE (
			    IF ( [CountRows_url_7_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: dash_name
		lineageTag: ffc76f43-8de8-4fd8-a2c1-a919cd8ab8cf

	measure dash_name_7_2_4 =
			CALCULATE (
			    IF ( [CountRows_url_7_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: dash_name
		lineageTag: be8a85f1-432a-47ba-89f8-2d121ac8366a

	measure dash_name_7_2_5 =
			CALCULATE (
			    IF ( [CountRows_url_7_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: dash_name
		lineageTag: 97b21e3d-e537-4a75-a3f5-4720a78fd3b7

	measure dash_name_7_2_6 =
			CALCULATE (
			    IF ( [CountRows_url_7_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: dash_name
		lineageTag: 653c399b-ed79-499c-8fd5-deb3dc442cf1

	measure dash_name_7_3_1 =
			CALCULATE (
			    IF ( [CountRows_url_7_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 92354e6f-6e76-4a24-83a1-1740d8148c88

	measure dash_name_7_4_1 =
			CALCULATE (
			    IF ( [CountRows_url_7_4] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 3d63fd81-3542-4b67-927f-e4235f9725ca

	measure dash_name_7_5_1 =
			CALCULATE (
			    IF ( [CountRows_url_7_5] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 9328a7a6-aed3-4a1d-8736-79f653526cc7

	measure dash_name_8_1_1 =
			CALCULATE (
			    IF ( [CountRows_url_8_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 2406e3e2-1ee6-46f1-99b3-7844637b76c3

	measure dash_name_8_2_1 =
			CALCULATE (
			    IF ( [CountRows_url_8_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: b5b7764f-35d7-4b74-a2cc-64f2e549e6be

	measure dash_name_8_3_1 =
			CALCULATE (
			    IF ( [CountRows_url_8_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: ada66c1a-d687-4940-89a7-168dbaea8378

	measure dash_name_8_4_1 =
			CALCULATE (
			    IF ( [CountRows_url_8_4] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: b30855d7-0657-4ada-945a-79dd57005caa

	measure dash_name_8_5_1 =
			CALCULATE (
			    IF ( [CountRows_url_8_5] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 97e0a20e-a355-441a-9346-6d140c96a624

	measure dash_name_8_6_1 =
			CALCULATE (
			    IF ( [CountRows_url_8_6] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: aa76c8ea-b313-49b4-9ee6-6261128e585e

	measure dash_name_8_7_1 =
			CALCULATE (
			    IF ( [CountRows_url_8_7] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: ab7e30bd-5f08-4af0-90b2-32aaa7453d5a

	measure dash_name_8_8_1 =
			CALCULATE (
			    IF ( [CountRows_url_8_8] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 8f91aa45-eee6-4dc0-8f37-009a6c630968

	measure dash_name_9_1_1 =
			CALCULATE (
			    IF ( [CountRows_url_9_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 3b76057e-b5db-4745-b14e-ed9879c28880

	measure dash_name_9_2_1 =
			CALCULATE (
			    IF ( [CountRows_url_9_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 17581206-7359-4811-bb57-533dd36f6dcf

	measure dash_name_9_3_1 =
			CALCULATE (
			    IF ( [CountRows_url_9_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: f96a9403-a97c-4ce9-9139-1bb1aaaf0c38

	measure dash_name_9_4_1 =
			CALCULATE (
			    IF ( [CountRows_url_9_4] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: df000ab3-d34d-4e39-8553-9e4212fb60ae

	measure dash_name_9_5_1 =
			CALCULATE (
			    IF ( [CountRows_url_9_5] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: d45ced60-9756-44d0-8e25-f26c27d998b3

	measure dash_name_9_6_1 =
			CALCULATE (
			    IF ( [CountRows_url_9_6] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 12083ffc-0df1-43b4-857b-ebb6e95af649

	measure dash_name_9_7_1 =
			CALCULATE (
			    IF ( [CountRows_url_9_7] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: c53542fd-c235-4e6a-addf-f8e62085c62b

	measure dash_name_2_6_1 =
			CALCULATE (
			    IF ( [CountRows_url_2_6] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 2559b8f1-8909-4586-a749-60efed37b2f3

	measure dash_name_3_5_1 =
			CALCULATE (
			    IF ( [CountRows_url_3_5] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 33e8d6ba-dc65-4870-8f52-5cabfc996a2f

	measure dash_name_3_6_1 =
			CALCULATE (
			    IF ( [CountRows_url_3_6] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: c274cb03-ba2e-4b07-8b72-031c966c66b7

	measure dash_name_4_5_1 =
			CALCULATE (
			    IF ( [CountRows_url_4_5] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 251ce5e1-79f7-4cbf-a313-eae2afe999e9

	measure dash_name_4_6_1 =
			CALCULATE (
			    IF ( [CountRows_url_4_6] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 7d4468db-f76e-4688-a96d-5630a4ef1ec0

	measure dash_name_5_6_1 =
			CALCULATE (
			    IF ( [CountRows_url_5_6] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 84a5b6b9-cd01-4bcc-bdc3-41b5a9abaef7

	measure dash_name_6_6_1 =
			CALCULATE (
			    IF ( [CountRows_url_6_6] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 406222ed-cd11-4e50-b905-005e506d1965

	measure dash_name_7_6_1 =
			CALCULATE (
			    IF ( [CountRows_url_7_6] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: d50ceb0d-3620-441f-8574-0ad2600e6a57

	measure dash_name_11_6_1 =
			CALCULATE (
			    IF ( [CountRows_url_11_6] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 6c867e72-dfa6-44ec-8667-83b2eb312fa4

	measure dash_name_10_3_2 =
			CALCULATE (
			    IF ( [CountRows_url_10_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: dash_name
		lineageTag: cdd53b2d-18d3-4c1e-908b-40b5d2229eef

	measure dash_name_10_3_3 =
			CALCULATE (
			    IF ( [CountRows_url_10_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: dash_name
		lineageTag: f96ef2ee-891a-41f7-b1db-54b1c1321e88

	measure dash_name_10_3_4 =
			CALCULATE (
			    IF ( [CountRows_url_10_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: dash_name
		lineageTag: 89e32403-b252-482b-abeb-aab86f1fbf7f

	measure dash_name_10_3_5 =
			CALCULATE (
			    IF ( [CountRows_url_10_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: dash_name
		lineageTag: 7dee6c6a-34fb-415f-a6cc-424fa22e6faa

	measure dash_name_10_6_1 =
			CALCULATE (
			    IF ( [CountRows_url_10_6] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 849d7f97-eff9-4e37-9ca8-3ffc6d999db8

	measure dash_name_10_7_1 =
			CALCULATE (
			    IF ( [CountRows_url_10_7] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: e9712a52-02ec-4e45-9ebd-6ad62a0bab0a

	measure dash_name_10_8_1 =
			CALCULATE (
			    IF ( [CountRows_url_10_8] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 3c5e351b-f725-4c0d-8eba-fe77df0f9db5

	measure dash_name_10_9_1 =
			CALCULATE (
			    IF ( [CountRows_url_10_9] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: d9109701-2bec-4631-b1e4-eca613b64be7

	measure dash_name_8_9_1 =
			CALCULATE (
			    IF ( [CountRows_url_8_9] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: eef01aa9-effe-41d1-af4c-f726e99a980a

	measure dash_name_9_8_1 =
			CALCULATE (
			    IF ( [CountRows_url_9_8] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 97611944-db38-437f-b7c6-3e3378b62e61

	measure dash_name_9_9_1 =
			CALCULATE (
			    IF ( [CountRows_url_9_9] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: b26f0ca8-4aa5-460d-b424-4e427b561464

	measure dash_name_12_3_1 =
			CALCULATE (
			    IF ( [CountRows_url_12_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: d5d2ee6e-c88b-405b-bb07-7e08d11e6c27

	measure dash_name_13_1_1 =
			CALCULATE (
			    IF ( [CountRows_url_13_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 67214694-8e78-431c-8f74-130f7dddcfdb

	measure dash_name_14_1_1 =
			CALCULATE (
			    IF ( [CountRows_url_14_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 9710c3df-f403-440c-bc50-3c564db4a37c

	measure dash_name_15_1_1 =
			CALCULATE (
			    IF ( [CountRows_url_15_1] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: dd058ca6-f8ef-4de2-a446-f61f6df01ca8

	measure dash_name_13_2_1 =
			CALCULATE (
			    IF ( [CountRows_url_13_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 20376ac1-cb4f-4ef7-96aa-7bd86295b1e1

	measure dash_name_14_2_1 =
			CALCULATE (
			    IF ( [CountRows_url_14_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 82e96611-47c3-4201-b181-86f9987a1a31

	measure dash_name_15_2_1 =
			CALCULATE (
			    IF ( [CountRows_url_15_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 1392dddb-b8ed-45c8-924d-509325fa1e1f

	measure dash_name_13_3_1 =
			CALCULATE (
			    IF ( [CountRows_url_13_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 63825dd0-f856-47d5-ba06-daedc8a80559

	measure dash_name_14_3_1 =
			CALCULATE (
			    IF ( [CountRows_url_14_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: a81335a6-3a4e-4ca4-9755-7519c0d5d5aa

	measure dash_name_15_3_1 =
			CALCULATE (
			    IF ( [CountRows_url_15_3] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 37767a7b-c605-4111-be65-c055e46db757

	measure dash_name_13_4_1 =
			CALCULATE (
			    IF ( [CountRows_url_13_4] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: f905f948-c360-4315-a37b-85e6e38a6aa9

	measure dash_name_14_4_1 =
			CALCULATE (
			    IF ( [CountRows_url_14_4] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 98efba02-ce65-46f3-bae0-e8ebb3563939

	measure dash_name_15_4_1 =
			CALCULATE (
			    IF ( [CountRows_url_15_4] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 4a4127ed-46f6-4aa7-9c32-7c9cedca29ad

	measure dash_name_13_5_1 =
			CALCULATE (
			    IF ( [CountRows_url_13_5] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 13ab3cef-6d0e-4e88-a2ae-90aa48f4c64f

	measure dash_name_14_5_1 =
			CALCULATE (
			    IF ( [CountRows_url_14_5] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: f35e684e-bef6-4324-9a8f-cd957274b53e

	measure dash_name_15_5_1 =
			CALCULATE (
			    IF ( [CountRows_url_15_5] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: e9da7c28-f947-4359-a43e-afa0a9164f25

	measure dash_name_13_6_1 =
			CALCULATE (
			    IF ( [CountRows_url_13_6] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 6a816a0f-3032-4605-a123-7a03c560d786

	measure dash_name_14_6_1 =
			CALCULATE (
			    IF ( [CountRows_url_14_6] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: d31c1304-c8da-4e49-aa6a-967c85aa4029

	measure dash_name_15_6_1 =
			CALCULATE (
			    IF ( [CountRows_url_15_6] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 4aefe990-236c-4ec5-abd9-08ee58a01234

	measure dash_name_13_7_1 =
			CALCULATE (
			    IF ( [CountRows_url_13_7] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 7983ad98-f45d-46a7-8e9f-858abdc6832d

	measure dash_name_14_7_1 =
			CALCULATE (
			    IF ( [CountRows_url_14_7] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 749d6c38-001c-408a-a90e-b3667bef351d

	measure dash_name_15_7_1 =
			CALCULATE (
			    IF ( [CountRows_url_15_7] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: ebb8b3fa-b857-4998-910a-61d66f8bd06e

	measure dash_name_13_8_1 =
			CALCULATE (
			    IF ( [CountRows_url_13_8] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 34e66af3-9337-4b26-ab6e-8b60310434c0

	measure dash_name_14_8_1 =
			CALCULATE (
			    IF ( [CountRows_url_14_8] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 1ed1b6be-8686-4557-93e6-aaa0b0a25082

	measure dash_name_15_8_1 =
			CALCULATE (
			    IF ( [CountRows_url_15_8] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 40473dfe-8b55-40fa-98ba-bb9585e7c692

	measure dash_name_13_9_1 =
			CALCULATE (
			    IF ( [CountRows_url_13_9] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: 50d2d194-faeb-4503-8919-565824a29fbb

	measure dash_name_14_9_1 =
			CALCULATE (
			    IF ( [CountRows_url_14_9] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: b2eee1b0-8884-47a8-8ec4-38606e04b438

	measure dash_name_15_9_1 =
			CALCULATE (
			    IF ( [CountRows_url_15_9] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: dash_name
		lineageTag: a6bc653e-259b-4bd0-ae42-c42475774a6a

	measure primeiro_char = UPPER(LEFT(USERPRINCIPALNAME(),2))
		displayFolder: geral
		lineageTag: e3d8e13f-69f0-4956-9649-ace361126447

	measure 'Username Validado 1' =
			
			VAR usuario =
			    USERPRINCIPALNAME ()
			VAR acharHashtag =
			    FIND ( "#", usuario, 1, 0 )
			VAR conta_ =
			    LEN ( usuario ) - LEN ( SUBSTITUTE ( usuario, "_", "" ) )
			VAR limpa =
			    MID ( usuario, FIND ( "#", usuario, 1, 0 ) + 1, LEN ( usuario ) - acharHashtag )
			VAR userlimpo =
			    IF (
			        LEFT ( limpa, 4 ) = "EXT#",
			        SUBSTITUTE ( LEFT ( USERPRINCIPALNAME (), acharHashtag - 1 ), "_", "@" ),
			        limpa
			    )
			VAR userFinal =
			    IF ( conta_ > 1, SUBSTITUTE ( userlimpo, "@", "_", 1 ), userlimpo )
			RETURN
			    userFinal
		displayFolder: geral
		lineageTag: c799cbb0-140d-4043-b495-daae3099d219

	measure page_name_1_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 4a17fff4-6b0f-4189-8a3f-e2ce91fe6983

	measure page_name_1_1_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: 40c2a150-60ab-4ef3-9fee-1c0add0cc6a4

	measure page_name_1_1_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_name
		lineageTag: 4f36f59d-d2ae-4527-8e3c-3e0a091f0e96

	measure page_name_1_1_4 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_name
		lineageTag: 2a34fb10-4429-4c49-8b50-61158800f8a1

	measure page_name_1_1_5 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_name
		lineageTag: 4548671b-05b9-4286-b077-84ec1a6f118a

	measure page_name_1_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 781caabb-487d-4704-bf34-57089b02b210

	measure page_name_1_2_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: ea048c84-e298-409a-97d0-0b9886f2357d

	measure page_name_1_2_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_name
		lineageTag: cd82852b-f9fc-46ec-96f5-cc4834f19b1e

	measure page_name_1_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 71f73864-5d25-487c-afc4-aa3763549c78

	measure page_name_1_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 4fccb4db-23ec-43e8-86dd-624175278bc5

	measure page_name_1_4_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: 025a2138-af22-42a0-a43c-0b411ac78a5f

	measure page_name_1_4_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_name
		lineageTag: 23479283-1b86-4d1a-9afe-dda6d1a564db

	measure page_name_1_4_4 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_name
		lineageTag: f652c10a-f9f4-4e02-896e-0076eb44fa06

	measure page_name_1_4_5 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_name
		lineageTag: 3e09fe56-6938-4b51-bf31-35cb3122b786

	measure page_name_1_4_6 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: page_name
		lineageTag: 07b0ca4b-0fa6-43b5-a3db-4594bb8622a4

	measure page_name_1_4_7 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 7
			)
		displayFolder: page_name
		lineageTag: 1c66d849-6359-40af-85c9-603d9955547c

	measure page_name_1_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 64c4712e-305a-4fea-86eb-291e2dfee112

	measure page_name_1_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 018bf462-195d-4ae0-a494-f5eb99e35ddf

	measure page_name_1_6_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: a39ffb60-01bb-4b7c-89ef-519ec29ed040

	measure page_name_1_6_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_name
		lineageTag: 7b91ca84-809f-456c-86dd-2d3b7ee94857

	measure page_name_11_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 0ed01d27-5382-47eb-afd8-3eb97c4290f0

	measure page_name_11_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 8891275c-1a6f-4e45-830d-0c1ed82c020a

	measure page_name_11_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 3a0d0d05-972d-4941-9291-d662293d6dc6

	measure page_name_11_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 7b0f8369-fffb-41f8-930c-32a8fa6277b1

	measure page_name_11_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 4ed5818b-7a64-4fbd-9e18-03de03acd711

	measure page_name_11_5_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: d6b3ecc9-29e1-48d0-a357-ef4cc487cc8f

	measure page_name_12_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 1bffed9f-1840-4cce-868d-3a0718bbca88

	measure page_name_12_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: ad1daf72-dc2c-4d5f-84be-473826dab845

	measure page_name_12_2_10 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 10
			)
		displayFolder: page_name
		lineageTag: ff1921f6-0725-4e80-aa36-a5960db62593

	measure page_name_12_2_11 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 11
			)
		displayFolder: page_name
		lineageTag: 4a0944df-d3ab-4fe7-9135-ead700ee9d3f

	measure page_name_12_2_12 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 12
			)
		displayFolder: page_name
		lineageTag: 469ea14f-2aca-4f93-9696-758f9be2cf80

	measure page_name_12_2_13 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 13
			)
		displayFolder: page_name
		lineageTag: 507b975a-4f5d-4d9b-97ab-1bbf34670a1a

	measure page_name_12_2_14 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 14
			)
		displayFolder: page_name
		lineageTag: 98621e4b-41b9-43cc-9a24-e56369bc60e3

	measure page_name_12_2_15 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 15
			)
		displayFolder: page_name
		lineageTag: 27b7d6d9-c649-4184-bb19-59c239de608a

	measure page_name_12_2_16 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 16
			)
		displayFolder: page_name
		lineageTag: 5e17f804-30e9-4cb5-992a-1bc04028ef53

	measure page_name_12_2_17 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 17
			)
		displayFolder: page_name
		lineageTag: 30c70eb3-9380-4616-8a3b-bf4d3281cf2c

	measure page_name_12_2_18 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 18
			)
		displayFolder: page_name
		lineageTag: 5af86029-931f-4dc9-8be9-fa58be4d4611

	measure page_name_12_2_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: 35c2a5d1-44e4-4990-be04-b3c91c8ab179

	measure page_name_12_2_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_name
		lineageTag: 8f0be5df-a6d5-451f-8994-24f32e8ccfbf

	measure page_name_12_2_4 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_name
		lineageTag: 26ba11a8-b243-420e-8260-388177b47aad

	measure page_name_12_2_5 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_name
		lineageTag: 6ecb44a5-6ae6-44f9-b90a-11bb94772a3f

	measure page_name_12_2_6 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: page_name
		lineageTag: 12e95d5e-fcc9-4979-bfdd-62a507697756

	measure page_name_12_2_7 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 7
			)
		displayFolder: page_name
		lineageTag: 04939eac-7134-431d-a45d-ad82deb27b2e

	measure page_name_12_2_8 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 8
			)
		displayFolder: page_name
		lineageTag: 3c0433a4-cd38-447a-ad37-dc4e5ba65859

	measure page_name_12_2_9 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 9
			)
		displayFolder: page_name
		lineageTag: 73b3883f-5b5a-4e00-b260-46b7f1374973

	measure page_name_2_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: c0fa700b-780e-4f4e-befb-37f6d10aab37

	measure page_name_2_1_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: 2b81ce11-7a76-4198-b329-1fc20275b668

	measure page_name_2_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 08552175-7dcc-434f-acd7-0143203cf935

	measure page_name_2_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 3de834bb-569c-48bd-85ed-6b18fdbc4abc

	measure page_name_2_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: f7b02d36-7552-4560-a9ff-9cf4f96b9df9

	measure page_name_2_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: f65d15e3-2e18-4148-9172-8c308dfef3e4

	measure page_name_3_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 79af17b6-59bb-43b7-b44b-012603f906a9

	measure page_name_3_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 74d26ab6-b181-46e5-a564-df4cc6b8130c

	measure page_name_3_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 0ef4ced2-8c26-4b28-a446-01b6f7d28660

	measure page_name_3_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 57360073-cb62-4d07-a260-5e4cdc5b0178

	measure page_name_4_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 2deecd63-2ae2-4087-acee-629f5796c1bf

	measure page_name_4_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: c6f16269-5b8e-4018-9f97-eb9dc4259b6e

	measure page_name_4_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: cc5585ff-d54a-4a18-a53a-4f8892a62b4c

	measure page_name_4_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 6753feef-8415-4304-b5cf-7cfa4f3ffe9d

	measure page_name_5_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: e6a68adf-6857-4e38-b7a6-22d90a606567

	measure page_name_5_1_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: 52a834b7-e94a-43a7-9bf7-cf9ad11ad5d1

	measure page_name_5_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 187ee33e-dd7a-4171-8141-84400f2ffac2

	measure page_name_5_2_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: 1c62ed29-9afd-4258-a2d2-36f29745531e

	measure page_name_5_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 84f6e113-506d-4eb2-bf7f-4831426b8586

	measure page_name_5_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: e3b6ade4-6b39-4acf-81b6-e11f7499f260

	measure page_name_5_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: ae48ea98-0370-4113-a7b2-67a7c80f2eb9

	measure page_name_6_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: e4b4e7d2-9f8e-45f7-9175-4447dbcac0a9

	measure page_name_6_1_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: 7522e067-ab69-43e8-b171-b0224032c00c

	measure page_name_6_1_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_name
		lineageTag: 8bb15ce2-dd8f-4498-b957-5026e0fc25ba

	measure page_name_6_1_4 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_name
		lineageTag: 68826d1d-7d46-4649-9b71-c4578f0dcf90

	measure page_name_6_1_5 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_name
		lineageTag: 15fd5004-0e0f-44e1-b396-e5645a5d6d4d

	measure page_name_6_1_6 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: page_name
		lineageTag: cc205411-9839-477d-af99-81f9fd3c5686

	measure page_name_6_1_7 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 7
			)
		displayFolder: page_name
		lineageTag: d54ccfbb-32a3-4fae-9aec-b5d0902aa071

	measure page_name_6_1_8 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 8
			)
		displayFolder: page_name
		lineageTag: 174c2a5c-1d83-41cc-acc8-c1d03e49c7c1

	measure page_name_6_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 11aff2e5-f6c2-4100-9843-4de0abba7b17

	measure page_name_6_2_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: 5eead8f1-b43c-4182-89f6-74e18101c08c

	measure page_name_6_2_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_name
		lineageTag: 55981b4a-620a-4210-a8e6-f24b4500fac6

	measure page_name_6_2_4 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_name
		lineageTag: 3bdd15cd-df4e-4334-bd44-85f11e693032

	measure page_name_6_2_5 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_name
		lineageTag: cdb8ddb2-7045-46c0-a01f-0bee211e224c

	measure page_name_6_2_6 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: page_name
		lineageTag: 1cf50469-0dc8-4d81-8d43-cfafa34ddcc1

	measure page_name_6_2_7 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 7
			)
		displayFolder: page_name
		lineageTag: 60d32688-abb8-41fa-b3ea-ad79dcf3c8ee

	measure page_name_6_2_8 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 8
			)
		displayFolder: page_name
		lineageTag: 2afa9c66-91ed-4028-a012-a9abf9aa5776

	measure page_name_6_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: d771fff4-8c0e-4e1e-9995-04fc7a014b83

	measure page_name_6_3_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: 68ea4350-573b-4516-a065-6012837ffca7

	measure page_name_6_3_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_name
		lineageTag: fc031275-8613-4fe1-bf46-027c83425083

	measure page_name_6_3_4 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_name
		lineageTag: bdb976c2-c2ac-49f3-8cd5-5d848ec015a3

	measure page_name_6_3_5 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_name
		lineageTag: 49510449-7049-4b7c-9a81-09e7feafbc56

	measure page_name_6_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 33461dcd-e959-4ff4-aa21-150d57d12de2

	measure page_name_6_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 18ae9b8b-17de-4190-85ab-665f074afa48

	measure page_name_7_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: f1486a14-ac99-4343-a377-6a3fe20bcb5d

	measure page_name_7_1_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: cd88ddf8-06a4-4b83-bbfc-8300bc0ca18b

	measure page_name_7_1_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_name
		lineageTag: a06ed428-6993-47d4-b0f6-c724e95e2a4d

	measure page_name_7_1_4 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_name
		lineageTag: 6bbd6871-abd9-4745-a4eb-4f18b975f038

	measure page_name_7_1_5 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_name
		lineageTag: e6e06ded-c944-4b03-8bb0-65757e669731

	measure page_name_7_1_6 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: page_name
		lineageTag: 0c6d91a5-ae5c-4c1b-a24c-ccb9ac41857a

	measure page_name_7_1_7 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 7
			)
		displayFolder: page_name
		lineageTag: 30d535d1-bba7-464c-9c23-216044ce0703

	measure page_name_7_1_8 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 8
			)
		displayFolder: page_name
		lineageTag: 60f3d258-8219-4859-be23-f1796fa92b08

	measure page_name_7_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: af72b21a-cf8a-4b51-b240-117baf78ac3c

	measure page_name_7_2_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: a4b818ba-3045-497d-b796-2d9e0eda0395

	measure page_name_7_2_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_name
		lineageTag: f3a91cac-5944-4db5-815e-4bc2ab5fa3b2

	measure page_name_7_2_4 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_name
		lineageTag: f34ab2f1-0643-4af9-870e-02408dc55686

	measure page_name_7_2_5 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_name
		lineageTag: 9a7af707-5add-4386-9c64-e1e7b9213d75

	measure page_name_7_2_6 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: page_name
		lineageTag: f7a58704-81ca-4975-a14a-89385f679b3e

	measure page_name_7_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: a07307fb-e98c-46bb-8ee5-29782079b32c

	measure page_name_7_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: a2310ed6-6e01-44de-8469-04afd967b682

	measure page_name_7_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 59c7ef13-2e0e-4b91-bc46-e9390c18481b

	measure page_name_2_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 526756d3-d0c5-44b9-9f10-2695a81c782f

	measure page_name_3_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 59264739-2caf-4797-89d9-ae626457170a

	measure page_name_3_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 4a450b35-60bb-4cda-935d-c010d9f31469

	measure page_name_4_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 8a3942d6-f8b4-4948-a90e-0da776f884e0

	measure page_name_4_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: daaa0817-d73b-414e-a14c-10cb07bafca5

	measure page_name_5_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: d6a3c34f-eeec-41e0-9e98-f0eb405c9384

	measure page_name_6_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 2a928b6b-827e-4cab-8ce7-5cb7a1d2582c

	measure page_name_7_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 8d0ab961-5dc1-49ab-8fea-45c9d0b2cb11

	measure page_name_11_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: afd854ef-f1b7-4d03-a25f-1a9ed2df3c31

	measure page_name_10_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: c0daf0a5-b085-4d36-af1f-af2539409e4e

	measure page_name_10_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 2b8ffe64-5c41-45e3-9862-2fdcaf37eae2

	measure page_name_10_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 905a54df-5379-4a7d-b7d5-31add6956744

	measure page_name_10_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 065e0091-54c6-45d4-b3aa-8242087c2a6f

	measure page_name_10_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 1d0f7b69-fc75-4dbd-bbf9-6be73bf78d05

	measure page_name_10_3_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: 9f34f995-0d58-4a14-91f1-1ccea1d7762e

	measure page_name_10_3_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_name
		lineageTag: 228a0f19-bba7-4673-aa38-9a900db2efed

	measure page_name_10_3_4 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_name
		lineageTag: 71027a1a-1cc0-406e-a450-a7ab80f42da3

	measure page_name_10_3_5 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_name
		lineageTag: 7bd8f7df-c04a-4c1c-b1b3-81473c8b3d1d

	measure page_name_10_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 77c278d6-ffc8-435c-8f4b-1a1b83823660

	measure page_name_8_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: b245c195-a2bf-431d-bab0-6e41e3cc19c2

	measure page_name_8_1_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_name
		lineageTag: c190f383-8f3a-451e-b55a-be243689b21e

	measure page_name_8_1_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: c960996b-d22f-4b54-b8af-6a5b654a3dcc

	measure page_name_8_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 16540d6d-a02b-4870-ac37-1eed6a8a05cc

	measure page_name_8_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: ba47e846-cc11-47f4-ba39-9700ab194e46

	measure page_name_8_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 899f4ffc-15ef-4baa-9376-4939a4ecae67

	measure page_name_8_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 0271a8fd-a41a-4bdb-a41c-b70c8836ff07

	measure page_name_8_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: cf057b43-bee4-4dc4-9616-cbabd86cba3a

	measure page_name_8_7_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: f0f0c637-6d10-481f-8c96-17fc2edc3de9

	measure page_name_8_8_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 55ee6258-8036-453d-987c-318b06a5fdb1

	measure page_name_8_9_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 2c23dcba-b875-4fb6-8152-e372ac30ecf9

	measure page_name_9_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 716c8f51-05ca-4797-a52e-5e4b11004801

	measure page_name_9_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 7e644cdd-bf89-4903-b102-c17c832a06a2

	measure page_name_9_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 186777a1-6516-4404-84b3-7fbd2150edc8

	measure page_name_9_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 5824bdb3-20d0-42e9-b04e-c3c6078c2895

	measure page_name_9_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: e856e069-c5e1-4de6-b208-0a4c52f6551b

	measure page_name_9_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 6939f346-817f-402c-ac8f-23526512fef9

	measure page_name_9_1_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_name
		lineageTag: 39854420-0172-4a9e-a80a-3d68be460cbd

	measure page_name_9_1_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: 87c3d027-2a4a-4ddf-9088-3e0f4443f655

	measure page_name_9_1_4 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_name
		lineageTag: 7a6e7b6d-5883-46b1-987a-46169ee996d6

	measure page_name_9_1_5 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_name
		lineageTag: 17b9c744-f29c-4b8f-97ee-969d87ce49a9

	measure page_name_9_1_6 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: page_name
		lineageTag: 4ce71233-3377-43d4-a869-2e76300cad3f

	measure page_name_10_7_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 81bb44a7-c40e-417e-b5ae-91e0a5d23e10

	measure page_name_10_8_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: adfdd037-063c-4312-baa1-f29fa66ad262

	measure page_name_10_9_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 4e173508-4d1e-4a4b-9a27-0ec3113032f2

	measure page_name_9_7_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 0f08dfa3-b8b5-4119-b20a-2648e4ef9d3b

	measure page_name_9_8_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: d99ab8d5-2478-4905-8835-b6020417cee5

	measure page_name_9_9_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 1ca03f0c-ed03-4fd1-b4e1-ed608f2f9ca8

	measure page_name_13_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 409b0666-ef51-4ee2-803b-2959e2f38ede

	measure page_name_12_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 345e62e8-edb1-4e6e-bf58-0bf2c40822f6

	measure page_name_14_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: a5426e2c-fbd0-4e7a-b556-04a57dd5d120

	measure page_name_15_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 1386d9fb-f243-4da1-ba30-b5b076b5ba99

	measure page_name_13_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 1ef4da98-07f4-4b4d-862b-b57b1c1bf2c9

	measure page_name_14_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: e4b190ea-c4ae-4b7b-865b-175d0d2f43e0

	measure page_name_15_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: bddc93ca-3424-4a57-9d01-b1b5a7de69fc

	measure page_name_13_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 63289d32-3a72-489c-be7c-0ee429a77048

	measure page_name_14_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 97f9572b-e8ab-4e80-8750-4398fce9a1c1

	measure page_name_15_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 45157f6d-c946-46b7-9baf-4b09d7e2a34c

	measure page_name_13_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 6bed50dc-52d3-4d33-9762-44becad57292

	measure page_name_14_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: c1fc4ee8-dce0-48c0-8ac8-bebe64b7896a

	measure page_name_15_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: e7b70372-0cfa-4649-b418-881128917e2f

	measure page_name_13_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 7e314798-53f6-4abd-970c-2faf7862d331

	measure page_name_14_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 75189b91-a199-47c3-953e-21edfebed8bb

	measure page_name_15_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 75bc005b-8793-4f0a-97b3-8dd085c8427b

	measure page_name_13_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 0c0ba519-75ae-4649-b18b-40e28c9fb678

	measure page_name_14_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: b1c9c138-3b76-487f-8d7b-cd6b8f533ad7

	measure page_name_15_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 082013ae-d780-4de0-a989-8aad2be9500e

	measure page_name_13_7_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 89bc0914-62e5-40d9-93de-b9732ce9c2a0

	measure page_name_14_7_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: d8399905-d207-4f53-b3d2-b6fe5f9f5b07

	measure page_name_15_7_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 3ddc5f33-1167-43c2-be08-07d27a4daf71

	measure page_name_13_8_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 50fda4dd-1787-4d72-9155-8477304c43ac

	measure page_name_14_8_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 1da7239e-6394-46d6-9e77-b425217c0ec5

	measure page_name_15_8_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 3acb4acb-196d-4b75-aa6a-d91362c04b64

	measure page_name_13_9_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 5b99a4ac-875c-47a6-9c72-5bc4f07412cf

	measure page_name_14_9_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 4359ec87-e33b-4b7b-9d9a-f2da30ec6ead

	measure page_name_15_9_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_name
		lineageTag: 5ed48249-7e47-46b9-861f-9ab236711f40

	measure dash_url_1_1_1 =
			CALCULATE (
			    IF ( [CountRows_1_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: e648d135-7548-4e69-89ea-cf371fc80b1e

	measure dash_url_1_1_2 =
			CALCULATE (
			    IF ( [CountRows_1_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_url
		lineageTag: 7d8ab8c1-fea4-4b73-9952-7a3389f0b258

	measure dash_url_1_1_3 =
			CALCULATE (
			    IF ( [CountRows_1_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_url
		lineageTag: 63115772-66b2-4c4c-b919-f39c173a4bc2

	measure dash_url_1_1_4 =
			CALCULATE (
			    IF ( [CountRows_1_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_url
		lineageTag: 6e730389-6f10-4f37-b28c-401d04a63b3c

	measure dash_url_1_1_5 =
			CALCULATE (
			    IF ( [CountRows_1_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_url
		lineageTag: 338c6dcc-d374-47e2-bfd6-3bb60b1574f8

	measure dash_url_1_2_1 =
			CALCULATE (
			    IF ( [CountRows_1_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 505ef665-e2b9-4e6e-aa24-76796b1a4350

	measure dash_url_1_2_2 =
			CALCULATE (
			    IF ( [CountRows_1_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_url
		lineageTag: 9660e942-1be3-4c0d-b919-3687c1686570

	measure dash_url_1_2_3 =
			CALCULATE (
			    IF ( [CountRows_1_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_url
		lineageTag: bdbab0b8-aecc-423c-ba1a-ebd461ecfee7

	measure dash_url_1_3_1 =
			CALCULATE (
			    IF ( [CountRows_1_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 631a0119-03fa-4fb8-a08b-0f0e5fbd1f40

	measure dash_url_1_4_1 =
			CALCULATE (
			    IF ( [CountRows_1_4] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 908d6c48-35fa-4806-b8b5-24c71fabe028

	measure dash_url_1_4_2 =
			CALCULATE (
			    IF ( [CountRows_1_4] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_url
		lineageTag: ee67cee6-91ec-49ec-b96e-2fd120b7e9e9

	measure dash_url_1_4_3 =
			CALCULATE (
			    IF ( [CountRows_1_4] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_url
		lineageTag: cbb1b38c-de24-420a-a20d-7a4752a36367

	measure dash_url_1_4_4 =
			CALCULATE (
			    IF ( [CountRows_1_4] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_url
		lineageTag: 6efcb561-5984-4e61-82f6-256936648c3f

	measure dash_url_1_4_5 =
			CALCULATE (
			    IF ( [CountRows_1_4] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_url
		lineageTag: 2bba70e5-021c-41cd-b4fc-995cd50f81fa

	measure dash_url_1_4_6 =
			CALCULATE (
			    IF ( [CountRows_1_4] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: page_url
		lineageTag: 4852abb3-7530-4cec-ac4b-968d3f09d88e

	measure dash_url_1_4_7 =
			CALCULATE (
			    IF ( [CountRows_1_4] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 7
			)
		displayFolder: page_url
		lineageTag: 02e5f936-a41a-459d-8294-43a619395bb6

	measure dash_url_1_5_1 =
			CALCULATE (
			    IF ( [CountRows_1_5] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: b895b14c-f61b-4b65-acee-73ff5ec9b215

	measure dash_url_1_6_1 =
			CALCULATE (
			    IF ( [CountRows_1_6] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 0dd2c06e-0bea-4798-91c3-a0df27bd0e3e

	measure dash_url_1_6_2 =
			CALCULATE (
			    IF ( [CountRows_1_6] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_url
		lineageTag: 1f7d1861-7eb7-42b8-8a92-b7d72ddba117

	measure dash_url_1_6_3 =
			CALCULATE (
			    IF ( [CountRows_1_6] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_url
		lineageTag: dd9a8031-9778-480d-87e6-ed26db72d830

	measure dash_url_10_1_1 =
			CALCULATE (
			    IF ( [CountRows_10_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 53fb01db-1eaf-4372-bf03-ff61071f811a

	measure dash_url_10_2_1 =
			CALCULATE (
			    IF ( [CountRows_10_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 6889b543-331f-42f5-afd6-37deed6b44f6

	measure dash_url_10_3_1 =
			CALCULATE (
			    IF ( [CountRows_10_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 5b6b3229-4329-42e7-8e08-548997b70cca

	measure dash_url_10_4_1 =
			CALCULATE (
			    IF ( [CountRows_10_4] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 835b7653-8566-458f-8fa0-5689f965a83f

	measure dash_url_10_5_1 =
			CALCULATE (
			    IF ( [CountRows_10_5] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: e64d3712-8149-4f60-846c-f523cde5843e

	measure dash_url_11_1_1 =
			CALCULATE (
			    IF ( [CountRows_11_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: b22acbbe-d88c-41de-bcee-899e788fbab0

	measure dash_url_11_2_1 =
			CALCULATE (
			    IF ( [CountRows_11_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: f20079c4-1306-4ae8-8583-62d5a661803e

	measure dash_url_11_3_1 =
			CALCULATE (
			    IF ( [CountRows_11_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 377d5122-6265-4b5f-8e4c-a78002836641

	measure dash_url_11_4_1 =
			CALCULATE (
			    IF ( [CountRows_11_4] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 38aa4d9b-92f7-4cfc-b648-faf040c30ae8

	measure dash_url_11_5_1 =
			CALCULATE (
			    IF ( [CountRows_11_5] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 45786c46-dfb8-4fd9-919a-7c1b8d445524

	measure dash_url_11_5_2 =
			CALCULATE (
			    IF ( [CountRows_11_5] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_url
		lineageTag: 173e19f1-eabd-4cd0-9171-99969f8031fe

	measure dash_url_12_1_1 =
			CALCULATE (
			    IF ( [CountRows_12_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: c5e0fd15-7e89-4cdb-ba13-d1180ec75d9f

	measure dash_url_12_2_1 =
			CALCULATE (
			    IF ( [CountRows_12_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: ace3c207-469f-4234-bc32-f77b01af0f8f

	measure dash_url_12_2_10 =
			CALCULATE (
			    IF ( [CountRows_12_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 10
			)
		displayFolder: page_url
		lineageTag: 65d66351-69c5-4000-ad96-eaeb90d3f463

	measure dash_url_12_2_11 =
			CALCULATE (
			    IF ( [CountRows_12_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 11
			)
		displayFolder: page_url
		lineageTag: 1e345e03-f377-4147-a2da-ef36e1167c21

	measure dash_url_12_2_12 =
			CALCULATE (
			    IF ( [CountRows_12_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 12
			)
		displayFolder: page_url
		lineageTag: 15a36be2-e11e-43c1-b3ef-4528bfa29980

	measure dash_url_12_2_13 =
			CALCULATE (
			    IF ( [CountRows_12_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 13
			)
		displayFolder: page_url
		lineageTag: 1e1a8ecb-cd2b-4492-b1cb-7cde5cbac5f5

	measure dash_url_12_2_14 =
			CALCULATE (
			    IF ( [CountRows_12_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 14
			)
		displayFolder: page_url
		lineageTag: 06af6957-0ac9-4f7e-a922-72588c4369e0

	measure dash_url_12_2_15 =
			CALCULATE (
			    IF ( [CountRows_12_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 15
			)
		displayFolder: page_url
		lineageTag: 26529803-8fbc-427c-8591-ed73046f8449

	measure dash_url_12_2_16 =
			CALCULATE (
			    IF ( [CountRows_12_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 16
			)
		displayFolder: page_url
		lineageTag: 4740c167-b189-4536-9d7d-49761b32946b

	measure dash_url_12_2_17 =
			CALCULATE (
			    IF ( [CountRows_12_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 17
			)
		displayFolder: page_url
		lineageTag: 24c8cb8a-58cf-4036-b09f-e1759aae0997

	measure dash_url_12_2_18 =
			CALCULATE (
			    IF ( [CountRows_12_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 18
			)
		displayFolder: page_url
		lineageTag: 25c9b03b-1e7d-49c8-9b07-c6737a6a0c9c

	measure dash_url_12_2_2 =
			CALCULATE (
			    IF ( [CountRows_12_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_url
		lineageTag: c02aa6d0-cf7a-4e39-be8e-53e3e9accf8c

	measure dash_url_12_2_3 =
			CALCULATE (
			    IF ( [CountRows_12_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_url
		lineageTag: fb563e4c-f7be-4f1e-9bd1-2eef869e01d2

	measure dash_url_12_2_4 =
			CALCULATE (
			    IF ( [CountRows_12_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_url
		lineageTag: 655d924b-353e-4c02-8582-63d94a7fad29

	measure dash_url_12_2_5 =
			CALCULATE (
			    IF ( [CountRows_12_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_url
		lineageTag: 4797c64f-6594-44f9-8ee5-d7d6572bae28

	measure dash_url_12_2_6 =
			CALCULATE (
			    IF ( [CountRows_12_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: page_url
		lineageTag: 6389f2d7-e617-4c66-a990-23499f9bfc77

	measure dash_url_12_2_7 =
			CALCULATE (
			    IF ( [CountRows_12_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 7
			)
		displayFolder: page_url
		lineageTag: a6acc19e-aacd-49f1-9b0b-f7fe04cb5f32

	measure dash_url_12_2_8 =
			CALCULATE (
			    IF ( [CountRows_12_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 8
			)
		displayFolder: page_url
		lineageTag: 21d2a572-2e23-4de0-af85-d0bc3877cab0

	measure dash_url_12_2_9 =
			CALCULATE (
			    IF ( [CountRows_12_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 9
			)
		displayFolder: page_url
		lineageTag: bf46a240-d9b3-4cd7-8aed-fb199676749d

	measure dash_url_2_1_1 =
			CALCULATE (
			    IF ( [CountRows_2_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: c5e0fd4b-80a0-4b3f-91e9-a6633f52d805

	measure dash_url_2_1_2 =
			CALCULATE (
			    IF ( [CountRows_2_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_url
		lineageTag: 54ce312a-df47-42d4-a7f7-313a301d471b

	measure dash_url_2_2_1 =
			CALCULATE (
			    IF ( [CountRows_2_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 6accbe46-72fb-4e8d-b098-a44f768ad743

	measure dash_url_2_3_1 =
			CALCULATE (
			    IF ( [CountRows_2_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 3d082f4c-4b40-43a2-a9de-1bf83a6045c1

	measure dash_url_2_4_1 =
			CALCULATE (
			    IF ( [CountRows_2_4] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 87f6a84c-c4f8-415a-b9bd-5931c3966c8b

	measure dash_url_2_5_1 =
			CALCULATE (
			    IF ( [CountRows_2_5] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 115f5deb-c63f-4051-b3fd-770d2cccedeb

	measure dash_url_3_1_1 =
			CALCULATE (
			    IF ( [CountRows_3_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 0335f513-0598-476e-a59c-8de13036aa45

	measure dash_url_3_2_1 =
			CALCULATE (
			    IF ( [CountRows_3_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 8b5a6156-8ecc-438d-b45c-870ecf093399

	measure dash_url_3_3_1 =
			CALCULATE (
			    IF ( [CountRows_3_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: b93123c0-56ee-4f68-adfd-2d64e514252e

	measure dash_url_3_4_1 =
			CALCULATE (
			    IF ( [CountRows_3_4] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 60775f00-79d2-42a9-bb31-b91daded7f20

	measure dash_url_4_1_1 =
			CALCULATE (
			    IF ( [CountRows_4_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 7cadafb2-b616-4102-8a18-40def0da6177

	measure dash_url_4_2_1 =
			CALCULATE (
			    IF ( [CountRows_4_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 014ac6ef-1c33-43f6-9078-e00f0d1c94fa

	measure dash_url_4_3_1 =
			CALCULATE (
			    IF ( [CountRows_4_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 5a9404bd-17fe-460c-a382-e3e4e65e0d7d

	measure dash_url_4_4_1 =
			CALCULATE (
			    IF ( [CountRows_4_4] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 0aeafef7-b19f-4229-8820-1e5b728542e1

	measure dash_url_5_1_1 =
			CALCULATE (
			    IF ( [CountRows_5_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 70859a2e-a552-44d3-9a7c-51858ad2a4ab

	measure dash_url_5_1_2 =
			CALCULATE (
			    IF ( [CountRows_5_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_url
		lineageTag: f4eead5e-9a12-4049-b51b-281c21caed1b

	measure dash_url_5_2_1 =
			CALCULATE (
			    IF ( [CountRows_5_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: a28c6459-bf84-4d1a-9e69-9e25fd0694bd

	measure dash_url_5_2_2 =
			CALCULATE (
			    IF ( [CountRows_5_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_url
		lineageTag: 6d10971b-91fd-4304-b355-d4238bcfb818

	measure dash_url_5_3_1 =
			CALCULATE (
			    IF ( [CountRows_5_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 90ad5a1a-7ffe-4c7c-8461-e47c85825e07

	measure dash_url_5_4_1 =
			CALCULATE (
			    IF ( [CountRows_5_4] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 994e18cf-f718-4986-a547-8bf4612fd2b1

	measure dash_url_5_5_1 =
			CALCULATE (
			    IF ( [CountRows_5_5] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: d334f7c6-76b1-46f8-870d-7173be7c17b8

	measure dash_url_6_1_1 =
			CALCULATE (
			    IF ( [CountRows_6_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: cbbba5a0-c035-4286-845d-0bfaa2dd6bf8

	measure dash_url_6_1_2 =
			CALCULATE (
			    IF ( [CountRows_6_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_url
		lineageTag: a482997d-261a-45aa-945d-f9e1277b57a7

	measure dash_url_6_1_3 =
			CALCULATE (
			    IF ( [CountRows_6_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_url
		lineageTag: 92604b8f-a248-4c6d-833a-574f2ab479e9

	measure dash_url_6_1_4 =
			CALCULATE (
			    IF ( [CountRows_6_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_url
		lineageTag: 81171eb7-fed8-4053-8ca7-bfcbf1b6dc03

	measure dash_url_6_1_5 =
			CALCULATE (
			    IF ( [CountRows_6_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_url
		lineageTag: 629d2a86-c1d3-47ab-9b3e-3b0494f340da

	measure dash_url_6_1_6 =
			CALCULATE (
			    IF ( [CountRows_6_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: page_url
		lineageTag: 206535a5-515a-4d41-8c41-f751c4dfe336

	measure dash_url_6_1_7 =
			CALCULATE (
			    IF ( [CountRows_6_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 7
			)
		displayFolder: page_url
		lineageTag: 043a1402-b8ee-4089-8c45-8603a4d35318

	measure dash_url_6_1_8 =
			CALCULATE (
			    IF ( [CountRows_6_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 8
			)
		displayFolder: page_url
		lineageTag: 72fd23c9-0f1c-440a-ae4c-b3ac2592d18b

	measure dash_url_6_2_1 =
			CALCULATE (
			    IF ( [CountRows_6_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 1ecca74d-8b2b-40c8-a14c-a1f604bd5dac

	measure dash_url_6_2_2 =
			CALCULATE (
			    IF ( [CountRows_6_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_url
		lineageTag: 0d70fb25-eba7-411c-ba80-062b33536a72

	measure dash_url_6_2_3 =
			CALCULATE (
			    IF ( [CountRows_6_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_url
		lineageTag: d7eb287a-1493-4b62-88f1-441f3600904d

	measure dash_url_6_2_4 =
			CALCULATE (
			    IF ( [CountRows_6_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_url
		lineageTag: ad16fa20-c808-46f3-9ef6-0517aa282de5

	measure dash_url_6_2_5 =
			CALCULATE (
			    IF ( [CountRows_6_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_url
		lineageTag: d9c94e93-382a-4caa-a8c6-f98241ba5bb5

	measure dash_url_6_2_6 =
			CALCULATE (
			    IF ( [CountRows_6_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: page_url
		lineageTag: 36796592-01d7-4c3b-876b-37f3c74d9fb9

	measure dash_url_6_2_7 =
			CALCULATE (
			    IF ( [CountRows_6_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 7
			)
		displayFolder: page_url
		lineageTag: c0c10aa7-7905-46e6-a4c3-633d71fbc033

	measure dash_url_6_2_8 =
			CALCULATE (
			    IF ( [CountRows_6_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 8
			)
		displayFolder: page_url
		lineageTag: 60164143-323a-4dc9-8606-f795f94b2c67

	measure dash_url_6_3_1 =
			CALCULATE (
			    IF ( [CountRows_6_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: e990623d-a3a8-4047-9691-c095acaf5abc

	measure dash_url_6_3_2 =
			CALCULATE (
			    IF ( [CountRows_6_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_url
		lineageTag: f5485af9-e620-44ab-a402-7679aa97db16

	measure dash_url_6_3_3 =
			CALCULATE (
			    IF ( [CountRows_6_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_url
		lineageTag: a7ed3ee4-6ef5-4897-9c2c-46e85ce722c4

	measure dash_url_6_3_4 =
			CALCULATE (
			    IF ( [CountRows_6_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_url
		lineageTag: cd0635b0-cc86-4277-b639-2a55bf0a239f

	measure dash_url_6_3_5 =
			CALCULATE (
			    IF ( [CountRows_6_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_url
		lineageTag: ecb1e1d8-f65b-4aff-90e8-d60a7be85f8c

	measure dash_url_6_4_1 =
			CALCULATE (
			    IF ( [CountRows_6_4] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 49fdcaa3-f9b0-43ff-a577-165775a8d862

	measure dash_url_6_5_1 =
			CALCULATE (
			    IF ( [CountRows_6_5] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: b57ab7a9-a43d-45c8-9c84-5a0ae07db107

	measure dash_url_7_1_1 =
			CALCULATE (
			    IF ( [CountRows_7_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: a97fc290-9bd4-4103-b5cb-1311869fcf22

	measure dash_url_7_1_2 =
			CALCULATE (
			    IF ( [CountRows_7_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_url
		lineageTag: 195196d1-6282-4df1-95d4-1889c3a41497

	measure dash_url_7_1_3 =
			CALCULATE (
			    IF ( [CountRows_7_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_url
		lineageTag: 127ef611-29c6-48e6-b7ee-2ca22c6fea69

	measure dash_url_7_1_4 =
			CALCULATE (
			    IF ( [CountRows_7_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_url
		lineageTag: 0d274a70-2738-4af3-9322-28abbb651ec3

	measure dash_url_7_1_5 =
			CALCULATE (
			    IF ( [CountRows_7_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_url
		lineageTag: 1556a2be-d621-48af-8295-efadfb8bf73b

	measure dash_url_7_1_6 =
			CALCULATE (
			    IF ( [CountRows_7_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: page_url
		lineageTag: 27a7ea7f-164a-4078-8835-4be74cf0728b

	measure dash_url_7_1_7 =
			CALCULATE (
			    IF ( [CountRows_7_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 7
			)
		displayFolder: page_url
		lineageTag: 5544b147-651c-4a5d-9eb2-d5987064f68a

	measure dash_url_7_1_8 =
			CALCULATE (
			    IF ( [CountRows_7_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 8
			)
		displayFolder: page_url
		lineageTag: f766916a-eea7-4e95-b113-49cc6059c958

	measure dash_url_7_2_1 =
			CALCULATE (
			    IF ( [CountRows_7_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: e2d4679d-e1a8-4bf7-9754-af6479d7da8d

	measure dash_url_7_2_2 =
			CALCULATE (
			    IF ( [CountRows_7_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_url
		lineageTag: 48c0328f-9022-4a8a-a326-b9da337f2814

	measure dash_url_7_2_3 =
			CALCULATE (
			    IF ( [CountRows_7_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_url
		lineageTag: ba84fd45-0930-4701-96f7-098ad6682b9f

	measure dash_url_7_2_4 =
			CALCULATE (
			    IF ( [CountRows_7_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_url
		lineageTag: 04e331ad-ed4b-4707-b914-d8acfded3de2

	measure dash_url_7_2_5 =
			CALCULATE (
			    IF ( [CountRows_7_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_url
		lineageTag: c1476bff-2023-4b51-bb6e-e7f284eaee8e

	measure dash_url_7_2_6 =
			CALCULATE (
			    IF ( [CountRows_7_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: page_url
		lineageTag: 5885469a-dbb5-481f-91f9-bd7b6d24a737

	measure dash_url_7_3_1 =
			CALCULATE (
			    IF ( [CountRows_7_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: b3431ce2-1281-4d23-8286-878989a7e001

	measure dash_url_7_4_1 =
			CALCULATE (
			    IF ( [CountRows_7_4] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 06607193-fb5a-42b1-be33-db88b682c5ee

	measure dash_url_7_5_1 =
			CALCULATE (
			    IF ( [CountRows_7_5] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: ea08ba1e-6157-46cf-8078-da00f8f6f633

	measure dash_url_8_1_1 =
			CALCULATE (
			    IF ( [CountRows_8_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 4cad2b78-d2d0-4dfc-8a5e-18cc45c98f66

	measure 'dash_url_8_2_1 ' =
			CALCULATE (
			    IF ( [CountRows_8_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: befe83e2-c620-42bb-b0ba-af5f919972c9

	measure dash_url_8_3_1 =
			CALCULATE (
			    IF ( [CountRows_8_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: b0c55520-0ac0-4c1a-bf89-bffa5412343f

	measure dash_url_8_4_1 =
			CALCULATE (
			    IF ( [CountRows_8_4] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: cffbec1e-5f56-41f8-82f1-a3e3d2814a7b

	measure dash_url_8_5_1 =
			CALCULATE (
			    IF ( [CountRows_8_5] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 27f846a3-7af9-4739-bcaa-c3e9d9d10d82

	measure dash_url_8_6_1 =
			CALCULATE (
			    IF ( [CountRows_8_6] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 8fce7b1f-8a6a-4d58-8cbf-3581c952bc27

	measure dash_url_8_7_1 =
			CALCULATE (
			    IF ( [CountRows_8_7] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: eae3357c-d4e2-4c14-a329-e97a6a0ddb41

	measure dash_url_8_8_1 =
			CALCULATE (
			    IF ( [CountRows_8_8] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: ab32334c-1fa3-4743-9e54-1dc3a0ad370b

	measure dash_url_9_1_1 =
			CALCULATE (
			    IF ( [CountRows_9_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: c654b410-6718-48f5-bad9-3e5cf4e56f97

	measure dash_url_9_2_1 =
			CALCULATE (
			    IF ( [CountRows_9_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 7a1855c5-e8e4-4374-b7ff-10f2cadd028b

	measure dash_url_9_3_1 =
			CALCULATE (
			    IF ( [CountRows_9_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 2e83903e-3d6a-457f-ac1e-622e3087f7fc

	measure dash_url_9_4_1 =
			CALCULATE (
			    IF ( [CountRows_9_4] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: bac0c097-e020-4cb3-92ac-c955df2d42cf

	measure dash_url_9_5_1 =
			CALCULATE (
			    IF ( [CountRows_9_5] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 2dad6368-1fc5-4e6a-bb44-b56f7c3f5d32

	measure dash_url_9_6_1 =
			CALCULATE (
			    IF ( [CountRows_9_6] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: d9305f92-bbc2-4364-b52e-6df3d943e9aa

	measure dash_url_9_7_1 =
			CALCULATE (
			    IF ( [CountRows_9_7] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 3f6d23a3-c5d2-47ab-b61c-d80e02970bc7

	measure dash_url_2_6_1 =
			CALCULATE (
			    IF ( [CountRows_2_5] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 319e751c-411d-4a76-9741-d7cd3869321f

	measure dash_url_3_5_1 =
			CALCULATE (
			    IF ( [CountRows_3_5] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 55fa5c2f-cfcb-400b-ac82-adf5ee5297ed

	measure dash_url_3_6_1 =
			CALCULATE (
			    IF ( [CountRows_3_6] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 4324ef8d-34d4-4c0e-b486-e6daaece0bea

	measure dash_url_4_6_1 =
			CALCULATE (
			    IF ( [CountRows_4_6] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: bdd1cba0-9a2f-4035-86aa-c1f6ddf9b4ab

	measure dash_url_4_5_1 =
			CALCULATE (
			    IF ( [CountRows_4_5] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 6c2c73b1-e567-430a-b16e-97a9cb34a241

	measure dash_url_5_6_1 =
			CALCULATE (
			    IF ( [CountRows_5_6] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 054456f7-2642-4233-a538-c02465ba17d9

	measure dash_url_6_6_1 =
			CALCULATE (
			    IF ( [CountRows_6_6] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 63a63a5d-5c5c-407a-93b4-732870d96d54

	measure dash_url_7_6_1 =
			CALCULATE (
			    IF ( [CountRows_7_6] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: e924f9d6-11e9-41a5-94ea-71b5bc4af30e

	measure dash_url_11_6_1 =
			CALCULATE (
			    IF ( [CountRows_11_6] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: c16e6e77-767a-4f79-a4f7-337407159fe8

	measure dash_url_10_3_2 =
			CALCULATE (
			    IF ( [CountRows_10_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_url
		lineageTag: ea30b94e-e09d-44a1-b147-101aac163dbb

	measure dash_url_10_3_3 =
			CALCULATE (
			    IF ( [CountRows_10_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_url
		lineageTag: 1817ccf3-7027-46fd-a6be-0b1f397c63ba

	measure dash_url_10_3_4 =
			CALCULATE (
			    IF ( [CountRows_10_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_url
		lineageTag: 979a4187-33f0-4eb9-8564-60760c153405

	measure dash_url_10_3_5 =
			CALCULATE (
			    IF ( [CountRows_10_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_url
		lineageTag: 0d45368b-9239-41bd-94a3-f1bea22ccc2c

	measure dash_url_10_6_1 =
			CALCULATE (
			    IF ( [CountRows_10_6] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 309289fe-35cc-4335-88c1-30c43416a49d

	measure dash_url_10_7_1 =
			CALCULATE (
			    IF ( [CountRows_10_7] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: a735e13e-073d-466c-8807-0cb8d277c274

	measure dash_url_10_8_1 =
			CALCULATE (
			    IF ( [CountRows_10_8] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 4ce85353-f705-42a5-9e4d-74a917ec615d

	measure dash_url_10_9_1 =
			CALCULATE (
			    IF ( [CountRows_10_9] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: c60a1236-7219-4b18-b80a-78ca7c3dc3ec

	measure dash_url_12_3_1 =
			CALCULATE (
			    IF ( [CountRows_12_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 71ceef08-7dac-4c10-b1e4-08a7ef2412df

	measure dash_url_8_9_1 =
			CALCULATE (
			    IF ( [CountRows_8_9] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 97bc8cdf-2f2b-400f-bd64-b3aa7f2b2ebd

	measure dash_url_9_9_1 =
			CALCULATE (
			    IF ( [CountRows_9_9] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 8797f4a9-7fc4-42cb-b0cf-c79bed81ed5e

	measure dash_url_9_8_1 =
			CALCULATE (
			    IF ( [CountRows_9_8] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: b0e4ef8a-32d2-426f-85dc-c8c865a51099

	measure dash_url_13_1_1 =
			CALCULATE (
			    IF ( [CountRows_13_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: b051728e-c9c1-4a7a-8713-f5f97ed96453

	measure dash_url_14_1_1 =
			CALCULATE (
			    IF ( [CountRows_14_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: de540eb7-45a0-4f14-a537-899f25600f70

	measure dash_url_15_1_1 =
			CALCULATE (
			    IF ( [CountRows_15_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 9bafaa46-a2ff-43f5-8dc8-4fca2e4fdd63

	measure dash_url_13_2_1 =
			CALCULATE (
			    IF ( [CountRows_13_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 96adde65-e0b2-44b7-84b6-56bee0ba2226

	measure dash_url_14_2_1 =
			CALCULATE (
			    IF ( [CountRows_14_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: b16f0ff0-9347-40be-96a2-0844c8788171

	measure dash_url_15_2_1 =
			CALCULATE (
			    IF ( [CountRows_15_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 7e2ef2ac-eda0-4160-99fa-08dfe76ecf18

	measure dash_url_13_3_1 =
			CALCULATE (
			    IF ( [CountRows_13_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 6b247c56-6fe5-411e-a894-45d4a672108b

	measure dash_url_14_3_1 =
			CALCULATE (
			    IF ( [CountRows_14_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: a947af2f-3ece-4a65-85b1-abf450eaca39

	measure dash_url_15_3_1 =
			CALCULATE (
			    IF ( [CountRows_15_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: a9533999-fe90-4896-a1dd-e59e0b8e6ce7

	measure dash_url_13_4_1 =
			CALCULATE (
			    IF ( [CountRows_13_4] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: d0f36dfb-f6ae-4f4a-b384-f0f4eaa299f1

	measure dash_url_14_4_1 =
			CALCULATE (
			    IF ( [CountRows_14_4] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: f707cade-cb92-484f-9c29-bb1cc0a8bd87

	measure dash_url_15_4_1 =
			CALCULATE (
			    IF ( [CountRows_15_4] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 531121de-b790-4208-8783-8efc0e664501

	measure dash_url_13_5_1 =
			CALCULATE (
			    IF ( [CountRows_13_5] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 0a66cece-41c6-4613-80b7-4a73c79666e6

	measure dash_url_14_5_1 =
			CALCULATE (
			    IF ( [CountRows_14_5] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 60e96d20-b925-422a-af6c-8df42746d9c4

	measure dash_url_15_5_1 =
			CALCULATE (
			    IF ( [CountRows_15_5] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: b1ffbc31-8eb3-4684-8b62-421e9e6c2985

	measure dash_url_13_6_1 =
			CALCULATE (
			    IF ( [CountRows_13_6] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: dc16079f-99d8-4180-9fd4-cfd173a107d5

	measure dash_url_14_6_1 =
			CALCULATE (
			    IF ( [CountRows_14_6] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 98b2d9af-c974-4a66-854b-fc9cf9f97975

	measure dash_url_15_6_1 =
			CALCULATE (
			    IF ( [CountRows_15_6] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 536d9c52-e3d0-488b-98ca-83b71c8ff544

	measure dash_url_13_7_1 =
			CALCULATE (
			    IF ( [CountRows_13_7] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 6faabf23-1482-4287-b4a0-650ba342a1ce

	measure dash_url_14_7_1 =
			CALCULATE (
			    IF ( [CountRows_14_7] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 263c301f-6f3d-4a85-a384-6bc9846b8897

	measure dash_url_15_7_1 =
			CALCULATE (
			    IF ( [CountRows_15_7] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 7332e44a-10ad-42b7-a1a0-a368708b3e5d

	measure dash_url_13_8_1 =
			CALCULATE (
			    IF ( [CountRows_13_8] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 99326de5-f769-472f-892e-f2dbd404d29a

	measure dash_url_14_8_1 =
			CALCULATE (
			    IF ( [CountRows_14_8] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 3b572c84-6263-41c2-80f7-bdcc0e912343

	measure dash_url_15_8_1 =
			CALCULATE (
			    IF ( [CountRows_15_8] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: b6449637-e4d8-467e-a6f5-029d08a365f0

	measure dash_url_13_9_1 =
			CALCULATE (
			    IF ( [CountRows_13_9] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: 65acd39e-9e7f-4a4b-98a8-51257aab4942

	measure dash_url_14_9_1 =
			CALCULATE (
			    IF ( [CountRows_14_9] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: d8fb9f58-7fcc-4047-b480-dcc6bc204e91

	measure dash_url_15_9_1 =
			CALCULATE (
			    IF ( [CountRows_15_9] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_url
		lineageTag: a1681e42-b316-4927-b91e-e6bbbffb1e82

	measure CountRows_url_1_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 1,
			        'dashboards_url'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: 432ae435-821e-4dd9-b6e6-cb240d0cef8b

	measure CountRows_url_1_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 1,
			        'dashboards_url'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 0ff29eac-9d22-43f8-b043-f364f8beca24

	measure CountRows_url_1_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 1,
			        'dashboards_url'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: a4669c87-3e48-416e-80b9-7bb5b98344c5

	measure CountRows_url_1_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 1,
			        'dashboards_url'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: a4f3843d-a5b9-4f6d-acd7-2219f6f0a9da

	measure CountRows_url_1_5 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 1,
			        'dashboards_url'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 44a0887e-f35e-4bec-afdc-ff7b1bf3a7f2

	measure CountRows_url_1_6 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 1,
			        'dashboards_url'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 6971d5d5-e19e-4074-88b1-41af78eef572

	measure CountRows_url_10_1 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 10,
			        'dashboards_url'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: 95bd32f7-c42b-442d-b6be-5e52af219988

	measure CountRows_url_10_2 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 10,
			        'dashboards_url'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: 37a4060f-93ff-4799-bb15-a383bd6ecad6

	measure CountRows_url_10_3 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 10,
			        'dashboards_url'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: ed0f3a52-06b0-4ead-863b-3e0d86f9351d

	measure CountRows_url_10_4 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 10,
			        'dashboards_url'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: d425ae0e-5e8b-42e6-b598-e994c4cc9cc0

	measure CountRows_url_10_5 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 10,
			        'dashboards_url'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: 3e94588e-11af-4441-96df-a8a5799dbe06

	measure CountRows_url_11_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 11,
			        'dashboards_url'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: ec7a4a51-a5dd-4a8d-9449-990f98d15e72

	measure CountRows_url_11_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 11,
			        'dashboards_url'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 225e5784-db20-4b04-a6e2-546d6a3e709c

	measure CountRows_url_11_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 11,
			        'dashboards_url'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: db45c32f-0c9d-4bda-8c9b-4bdffb6c1055

	measure CountRows_url_11_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 11,
			        'dashboards_url'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: da719403-f00e-4f1f-b77f-8d8d82e4ffd1

	measure CountRows_url_11_5 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 11,
			        'dashboards_url'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 23c1d289-be06-4c93-bc74-f18c2973913c

	measure CountRows_url_12_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 12,
			        'dashboards_url'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: f4a50dd6-1e95-4275-85e9-252f371e41b7

	measure CountRows_url_12_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 12,
			        'dashboards_url'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: cc7d21a0-4c75-4e15-aa18-d23d7105e88f

	measure CountRows_url_2_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 2,
			        'dashboards_url'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 343e994c-74ca-4fff-84cf-bc846c116071

	measure CountRows_url_2_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 2,
			        'dashboards_url'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: b7fa1123-e79f-4a7a-82a0-3306cfe43d0a

	measure CountRows_url_2_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 2,
			        'dashboards_url'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: 3025cd4d-01a5-4822-80dc-7fccad64a127

	measure CountRows_url_2_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 2,
			        'dashboards_url'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: 866fac2c-6240-42e6-a20f-e64508db047f

	measure CountRows_url_2_5 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 2,
			        'dashboards_url'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 8bac06e8-80f3-4a59-972b-c63455ba8b0d

	measure CountRows_url_2_6 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 2,
			        'dashboards_url'[id_dashboard] = 6
			    ) >= 1,
			    1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 890249f8-463f-4baa-8d0b-fd4783e5f724

	measure CountRows_url_3_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 3,
			        'dashboards_url'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: e84bd713-9476-446e-a289-fa84b4d1d667

	measure CountRows_url_3_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 3,
			        'dashboards_url'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: ac066f25-4a49-4f41-a207-6b114c2a6257

	measure CountRows_url_3_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 3,
			        'dashboards_url'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 4b39700d-89c9-478e-8714-d3d9dcdaf02d

	measure CountRows_url_3_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 3,
			        'dashboards_url'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: f528b92c-3769-4c7f-8b98-44fe26ce7943

	measure CountRows_url_4_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 4,
			        'dashboards_url'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 1f917e5d-a592-4eb5-8659-f745acadfe40

	measure CountRows_url_4_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 4,
			        'dashboards_url'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 1a2c23ee-148f-4bbd-86da-1ad84497d15e

	measure CountRows_url_4_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 4,
			        'dashboards_url'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: eafe3a21-7275-4a33-b2d3-faec45aa501e

	measure CountRows_url_4_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 4,
			        'dashboards_url'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 0ce3f26a-037b-422d-883f-02d93668010d

	measure CountRows_url_5_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 5,
			        'dashboards_url'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: b1bd421c-09cb-466a-9eab-a6dc20e5b0f6

	measure CountRows_url_5_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 5,
			        'dashboards_url'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 04c7013b-dafa-4516-b35a-df322b7ac3d6

	measure CountRows_url_5_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 5,
			        'dashboards_url'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 947fd403-e01a-4985-9483-9960797c62e2

	measure CountRows_url_5_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 5,
			        'dashboards_url'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 7ff8eece-0127-4f38-b03e-1330d67f0039

	measure CountRows_url_5_5 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 5,
			        'dashboards_url'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 9f63c82d-8770-437b-8aba-71a33a90901c

	measure CountRows_url_6_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 6,
			        'dashboards_url'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: c2d1de92-fe96-4ce5-9ffd-384c5bac020a

	measure CountRows_url_6_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 6,
			        'dashboards_url'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 3225d894-8dfd-422c-a73a-03aa466116f4

	measure CountRows_url_6_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 6,
			        'dashboards_url'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 14aa2453-f8ec-41e9-b766-8d926c4be9e8

	measure CountRows_url_6_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 6,
			        'dashboards_url'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: da70e650-a37d-4577-b228-186ebaf51dd4

	measure CountRows_url_6_5 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 6,
			        'dashboards_url'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 97fe02a8-e36f-4012-8e92-5d6c9fc15152

	measure CountRows_url_7_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 7,
			        'dashboards_url'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 437bcb50-8995-4bfa-b936-ae1dee1e4a42

	measure CountRows_url_7_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 7,
			        'dashboards_url'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 2ba855f4-eeb7-4438-82db-9cf075c2bfc4

	measure CountRows_url_7_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 7,
			        'dashboards_url'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 1944e942-1faf-4a0f-aaf1-b6802fe2a3de

	measure CountRows_url_7_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 7,
			        'dashboards_url'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 23e89f77-f0d8-4447-bf74-a82352a2991f

	measure CountRows_url_7_5 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 7,
			        'dashboards_url'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 715faf74-5ed3-474f-a258-5cf8650eccf6

	measure CountRows_url_8_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 8,
			        'dashboards_url'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: acceb669-f126-409a-99ff-4c5838d6c62e

	measure CountRows_url_8_2 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 8,
			        'dashboards_url'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: 81ecc2a9-0881-4f12-9376-a1a83440a0dd

	measure CountRows_url_8_3 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 8,
			        'dashboards_url'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: 117f4c00-b2a7-40fa-b634-5503f1c4abad

	measure CountRows_url_8_4 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 8,
			        'dashboards_url'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: 10cd226f-a46f-4e9b-af5a-37c381c6f94e

	measure CountRows_url_8_5 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 8,
			        'dashboards_url'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: 155eea0f-19a8-477a-8d4e-2e1be401fedf

	measure CountRows_url_8_6 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 8,
			        'dashboards_url'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: 3979be3d-9f5d-471e-97dc-d825fa4bf407

	measure CountRows_url_8_7 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 8,
			        'dashboards_url'[id_dashboard] = 7) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: 3c7c4e95-dda6-4dbc-818b-f2f3d49cd88e

	measure CountRows_url_8_8 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 8,
			        'dashboards_url'[id_dashboard] = 8) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: 9a4319c2-0602-4ef1-bc99-fd5c3e3bfdc6

	measure CountRows_url_9_1 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 9,
			        'dashboards_url'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: 0a862fd6-37ae-4501-98eb-d508ca22c714

	measure CountRows_url_9_2 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 9,
			        'dashboards_url'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: 906ee23f-ce67-4126-a60a-322af943c560

	measure CountRows_url_9_3 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 9,
			        'dashboards_url'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: de4f4edb-e756-4dd8-97f3-6d50fe0988a2

	measure CountRows_url_9_4 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 9,
			        'dashboards_url'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: b349c016-0a7e-4bf7-b2f9-0aa4a74d97ef

	measure CountRows_url_9_5 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 9,
			        'dashboards_url'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: 8776c44e-602d-4b15-9460-7859c27683b2

	measure CountRows_url_9_6 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 9,
			        'dashboards_url'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: 97466330-17d2-45c3-a23e-4f3f626d99aa

	measure CountRows_url_9_7 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 9,
			        'dashboards_url'[id_dashboard] = 7) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: c1d9a8d4-c7e0-4374-b241-db8d397c6750

	measure CountRows_url_3_5 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 3,
			        'dashboards_url'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 6dc73185-3ae8-484a-a9a9-645eff69d139

	measure CountRows_url_3_6 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 3,
			        'dashboards_url'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 0b4c9c18-ac13-44ca-97e0-8969d01a1709

	measure CountRows_url_4_5 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 4,
			        'dashboards_url'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 6e503134-7ee0-4ec8-8f6b-499d8ff36f0c

	measure CountRows_url_4_6 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 4,
			        'dashboards_url'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: ab625247-e47f-4714-b8b2-aac68928b36f

	measure CountRows_url_5_6 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 5,
			        'dashboards_url'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: ffa8c376-71d3-4601-9bc7-1c87ccdf8099

	measure CountRows_url_6_6 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 6,
			        'dashboards_url'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 6b3de391-b8b7-46cd-8db8-19a61ef1bcf9

	measure CountRows_url_7_6 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 7,
			        'dashboards_url'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: f45244f0-e480-4a40-9818-8b0d1daefeea

	measure CountRows_url_11_6 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 11,
			        'dashboards_url'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 15abe97b-ae66-4510-8a76-8fb4d8a09cd5

	measure CountRows_url_10_6 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 10,
			        'dashboards_url'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: 154f3b4d-2360-461b-a782-99733d51a400

	measure CountRows_url_10_7 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 10,
			        'dashboards_url'[id_dashboard] = 7) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: 948dec74-0e54-4c67-a2b0-55ecb95a376f

	measure CountRows_url_10_8 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 10,
			        'dashboards_url'[id_dashboard] = 8) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: bd1270c8-4209-4659-ad5d-f2a42291482e

	measure CountRows_url_10_9 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 10,
			        'dashboards_url'[id_dashboard] = 9) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: d08d9227-7756-44c0-9aec-c4c843b786d1

	measure CountRows_url_12_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 12,
			        'dashboards_url'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 275ab635-4127-41b3-85f5-d5c65f55d7e6

	measure CountRows_url_8_9 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 8,
			        'dashboards_url'[id_dashboard] = 9) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: 6582bedb-3dd0-4589-ac51-ae2e82e51163

	measure CountRows_url_9_9 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 9,
			        'dashboards_url'[id_dashboard] = 9) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: 6a85cdbf-3edd-4cec-9f58-1a1dfcd14fe8

	measure CountRows_url_9_8 =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 9,
			        'dashboards_url'[id_dashboard] = 8) >= 1, 1,
			    0
			)
		formatString: 0
		displayFolder: countrows_url
		lineageTag: 39e5bc8e-a1e4-40d1-9694-3e30a7daac9a

	measure CountRows_url_14_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 14,
			        'dashboards_url'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 8231ca61-ea48-489a-9f7a-ab36bee0bdcc

	measure CountRows_url_15_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 15,
			        'dashboards_url'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 603883ba-68a1-417e-8358-d984acd69029

	measure CountRows_url_13_1 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 13,
			        'dashboards_url'[id_dashboard] = 1) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 23835fd9-45f1-4603-983e-fcbaec41f13b

	measure CountRows_url_13_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 13,
			        'dashboards_url'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 86184238-07fb-422f-b2fe-37b8f985b11b

	measure CountRows_url_14_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 14,
			        'dashboards_url'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 4529fea3-3635-423c-ad5e-100964b82002

	measure CountRows_url_15_2 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 15,
			        'dashboards_url'[id_dashboard] = 2) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 2fa3f396-e35f-45d5-8d35-741e57f0e601

	measure CountRows_url_13_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 13,
			        'dashboards_url'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: f9e1ae80-7e45-4ef7-8190-9ee92940f28f

	measure CountRows_url_14_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 14,
			        'dashboards_url'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 0e5b04c1-a533-4b78-a0a5-242ac264d06b

	measure CountRows_url_15_3 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 15,
			        'dashboards_url'[id_dashboard] = 3) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: bcfbb853-4809-4df8-91f0-c32efead1970

	measure CountRows_url_13_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 13,
			        'dashboards_url'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 24834e9a-0b65-408a-ac81-90032a3c704c

	measure CountRows_url_14_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 14,
			        'dashboards_url'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 63d00d22-89d9-4ccd-838a-a6ad076f91b6

	measure CountRows_url_15_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 15,
			        'dashboards_url'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: acee42e6-3f11-48e5-959e-3d7b58e5d9c4

	measure CountRows_url_13_5 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 13,
			        'dashboards_url'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: aeb4e951-af9b-4a46-bec5-9cab129b04ac

	measure CountRows_url_14_5 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 14,
			        'dashboards_url'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 13130f42-9f2d-4f5f-8aae-2adc516acc9d

	measure CountRows_url_15_5 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 15,
			        'dashboards_url'[id_dashboard] = 5) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: ecffb7e0-3ebb-4789-b0c4-d908ae6ef197

	measure CountRows_url_13_6 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 13,
			        'dashboards_url'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 4f821189-37b9-4fd1-b7ad-ebd44952045a

	measure CountRows_url_14_6 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 14,
			        'dashboards_url'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 71b4b910-ea55-42c8-85d7-f796c54e5378

	measure CountRows_url_15_6 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 15,
			        'dashboards_url'[id_dashboard] = 6) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 81f85b8c-b48c-456a-8bfa-732b2b66e76f

	measure CountRows_url_13_7 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 13,
			        'dashboards_url'[id_dashboard] = 7) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: c400692f-e3a7-4fa3-9ea7-1b5c809e4cb7

	measure CountRows_url_14_7 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 14,
			        'dashboards_url'[id_dashboard] = 7) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 8a874990-ef5a-4e5e-a4b7-4962db307a56

	measure CountRows_url_15_7 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 15,
			        'dashboards_url'[id_dashboard] = 7) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: aa9a59ed-0c57-4547-820d-b6fe3a0148d2

	measure CountRows_url_13_8 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 13,
			        'dashboards_url'[id_dashboard] = 8) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 7848cb5b-cbd2-448f-9b74-3050e9f4da67

	measure CountRows_url_14_8 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 14,
			        'dashboards_url'[id_dashboard] = 8) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: fb7bccb3-e51a-4e18-9bb5-531cfbc774ab

	measure CountRows_url_15_8 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 15,
			        'dashboards_url'[id_dashboard] = 8) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 3b40a7e0-026e-4a24-a39c-866dd96aa557

	measure CountRows_url_13_9 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 13,
			        'dashboards_url'[id_dashboard] = 9) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: 45123d47-fd48-41ba-b055-d8abc25f4e56

	measure CountRows_url_14_9 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 14,
			        'dashboards_url'[id_dashboard] = 9) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: fb115a25-f388-4575-a410-8201d8f35b3a

	measure CountRows_url_15_9 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dashboards_url' ),
			        'dashboards_url'[id_vertical] = 15,
			        'dashboards_url'[id_dashboard] = 9) >= 1, 1,
			    0
			)
		displayFolder: countrows_url
		lineageTag: e6aa0c96-2af1-4a7c-86ae-be7f5c42d22e

	measure page_header_name_1_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 89631107-52ae-4eb0-991d-861cd8d46be1

	measure page_header_name_1_1_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_header_name
		lineageTag: 6ca72dcf-03e5-4ef3-ae9a-f98e92028976

	measure page_header_name_1_1_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_header_name
		lineageTag: 96ee79f8-1aa0-4ace-a35e-b5643f6ea414

	measure page_header_name_1_1_4 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_header_name
		lineageTag: 05369d6b-42dd-44a6-9f75-2868f7f84c2d

	measure page_header_name_1_1_5 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_header_name
		lineageTag: ed5c2719-beb4-45a1-9de3-44ee7ea71dc8

	measure page_header_name_1_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 90cc8267-c875-45cf-8ee4-4fcd2553d781

	measure page_header_name_1_2_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_header_name
		lineageTag: 76a06af2-fdb5-48b3-b2c6-93f6998ba0e5

	measure page_header_name_1_2_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_header_name
		lineageTag: 18e18868-dce4-49dc-8072-f8185fe82869

	measure page_header_name_1_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: f3fc446d-1452-4028-8ffa-4ffd18bde57e

	measure page_header_name_1_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 9a98243e-661a-4295-a8f9-5186e0848fe3

	measure page_header_name_1_4_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_header_name
		lineageTag: c200ead2-e68b-450e-83b2-e8685cb4a680

	measure page_header_name_1_4_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_header_name
		lineageTag: 96238ecb-c2d3-4cec-bcc1-344c526aaaff

	measure page_header_name_1_4_4 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_header_name
		lineageTag: 05b2e006-6056-473a-914e-d92c6ae475b5

	measure page_header_name_1_4_5 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_header_name
		lineageTag: 9f39e6a9-9bc1-4d08-aca7-e0a1cb2fa2f1

	measure page_header_name_1_4_6 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: page_header_name
		lineageTag: 9110a48d-6f9a-484f-a2ef-0a8217ab7895

	measure page_header_name_1_4_7 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 7
			)
		displayFolder: page_header_name
		lineageTag: d52c3640-5a4d-4dfa-b135-7b5af36dc567

	measure page_header_name_1_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 20c3e92a-acfd-4460-b374-b92bcb756190

	measure page_header_name_1_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 4b6d3961-48a5-4fb8-90bf-4fc98430d55d

	measure page_header_name_1_6_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_header_name
		lineageTag: 7b8886ad-8d49-4896-a363-1b6cebac5e11

	measure page_header_name_1_6_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 1,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_header_name
		lineageTag: ab73cd43-9cb5-41dc-8f57-f02242f0f28d

	measure page_header_name_10_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 945186a6-6f55-40a8-b73e-565f7c622fcc

	measure page_header_name_10_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 48f44354-13ee-42fa-a41a-3095bdfae408

	measure page_header_name_10_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: fa083ed1-dcc4-497d-8dc1-a570ef51001c

	measure page_header_name_10_3_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_header_name
		lineageTag: bdce59d2-1a66-4af9-8f77-6b07c9508bdc

	measure page_header_name_10_3_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_header_name
		lineageTag: beac8492-ee9d-4916-9422-09d286b2a0ed

	measure page_header_name_10_3_4 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_header_name
		lineageTag: e6b4e2a3-ee73-4e3b-9376-adf4b7ce58b4

	measure page_header_name_10_3_5 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_header_name
		lineageTag: 6334dfe4-fafa-4d6a-94f4-75a195489425

	measure page_header_name_10_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard]) & " - " & MAX ( 'dashboards_url'[name_page]),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 8e041e72-eacd-456d-bd66-aadfb64ef180

	measure page_header_name_10_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 2d9698a7-ab6b-4d37-a821-e2a26471c19d

	measure page_header_name_10_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 4059db5d-e968-42e8-ab21-aaaad92f7a53

	measure page_header_name_11_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: df7c5255-9099-4d43-b722-2117209805b8

	measure page_header_name_11_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: bdb557f2-4221-4bdb-aa23-cab9d044762b

	measure page_header_name_11_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: e43af3b0-230f-4156-a977-00c8e3e3697d

	measure page_header_name_11_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: abc114d0-d948-4fdb-84c9-1109b7b35f2a

	measure page_header_name_11_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 0c6ee3af-18ed-457e-9f59-f31f98d3e823

	measure page_header_name_11_5_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_header_name
		lineageTag: 3daecae2-59a8-4ca3-bbde-f0da4cb4a27e

	measure page_header_name_11_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 11,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 1718a192-fbc6-4bcf-8cd2-52b0da9e722a

	measure page_header_name_12_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 3f9fc1fc-da70-4b9d-9b75-f88449d2435e

	measure page_header_name_12_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: e6d0d497-61f6-4a07-90cf-0b4da4ea3128

	measure page_header_name_12_2_10 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 10
			)
		displayFolder: page_header_name
		lineageTag: f4f7111b-eed1-4463-8d89-5ae7284ffd52

	measure page_header_name_12_2_11 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 11
			)
		displayFolder: page_header_name
		lineageTag: 6149b003-039d-4db0-88c7-0d04ff78f945

	measure page_header_name_12_2_12 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 12
			)
		displayFolder: page_header_name
		lineageTag: a7034756-20bb-4216-868a-cddb6b8e3a2b

	measure page_header_name_12_2_13 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 13
			)
		displayFolder: page_header_name
		lineageTag: de6576ec-0d91-4642-92a1-bdd4ee2540aa

	measure page_header_name_12_2_14 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 14
			)
		displayFolder: page_header_name
		lineageTag: 86a217b9-65a3-41ff-a7bb-b1885d09e9a3

	measure page_header_name_12_2_15 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 15
			)
		displayFolder: page_header_name
		lineageTag: d0fcf580-3698-481a-9b20-ff3cf0c8e2f5

	measure page_header_name_12_2_16 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 16
			)
		displayFolder: page_header_name
		lineageTag: 16f36901-0107-4477-ae3f-9d62e3e84105

	measure page_header_name_12_2_17 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 17
			)
		displayFolder: page_header_name
		lineageTag: 6c06c6c6-72b6-47d2-86fe-87717e8f2a3d

	measure page_header_name_12_2_18 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 18
			)
		displayFolder: page_header_name
		lineageTag: dbdccf62-8e74-4b07-b40b-f425ae3f0931

	measure page_header_name_12_2_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_header_name
		lineageTag: ccae3d06-7acc-43f8-b73a-1502f3c487e4

	measure page_header_name_12_2_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_header_name
		lineageTag: c19043e8-4837-4180-8fce-3f53ec984154

	measure page_header_name_12_2_4 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_header_name
		lineageTag: 66232c4b-b322-4bb6-8f1d-d211a2b483d0

	measure page_header_name_12_2_5 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_header_name
		lineageTag: 11e47ae3-7b40-4a0a-b391-fa89a3086603

	measure page_header_name_12_2_6 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: page_header_name
		lineageTag: c7b7d115-15b9-4d9e-9b85-fd37cfdf7e72

	measure page_header_name_12_2_7 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 7
			)
		displayFolder: page_header_name
		lineageTag: 99dfb621-fbf0-427e-a3e3-b9cb0b8a03d1

	measure page_header_name_12_2_8 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 8
			)
		displayFolder: page_header_name
		lineageTag: 1222bfcb-b1c2-4b9b-a6c0-24c7a3c0d9e7

	measure page_header_name_12_2_9 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 9
			)
		displayFolder: page_header_name
		lineageTag: c98e09e4-981d-4580-a6f3-44731ce37a69

	measure page_header_name_2_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 934e1154-3e63-40cc-9241-ae26dcc2abe5

	measure page_header_name_2_1_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_header_name
		lineageTag: 0486ed6e-f08e-4e56-9340-f61e37bbb488

	measure page_header_name_2_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 9622765e-70a4-48ad-b0e8-1bdf8bf26feb

	measure page_header_name_2_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: a3c171e3-588f-4cf8-a612-97b074470ac2

	measure page_header_name_2_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 2e2c5c71-7cb4-4af1-93d8-42db9133c291

	measure page_header_name_2_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 3cd11f01-9433-4adc-a4b4-a7779795f9db

	measure page_header_name_2_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 2,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 2a5b1429-c1d7-4119-9851-af41ccdb8ec8

	measure page_header_name_3_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 1cd26629-7fbb-4219-93f7-81f9d0b6707c

	measure page_header_name_3_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: afeec5a5-a48f-40c4-9df4-0c54cfb1e9f7

	measure page_header_name_3_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 746016c2-8c26-4e07-9a21-024dce5a0155

	measure page_header_name_3_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 3f633246-8747-4282-b6f8-08bf9f108d6c

	measure page_header_name_3_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 58e8c65a-8698-4e89-b2fa-97eff5ef77be

	measure page_header_name_3_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 3,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 73eae73e-f76b-40e3-a477-8b282bdf33cc

	measure page_header_name_4_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 29e0c4be-f502-40cd-8f1d-389355061cb3

	measure page_header_name_4_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: c9e77831-7757-4498-bb5f-66868b92e98d

	measure page_header_name_4_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 6bca6bcc-8137-4c8d-afa1-a325c5a6b9af

	measure page_header_name_4_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 952db0b2-8c92-4d4b-aed6-ae2dd578a782

	measure page_header_name_4_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 288bf312-c364-47a7-be08-9d394b25b758

	measure page_header_name_4_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 4,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 7c8ff185-cd55-4f1b-9a15-f6e320db7065

	measure page_header_name_5_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: e3dbae89-8fad-4677-be83-1a5c4c3dd11c

	measure page_header_name_5_1_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_header_name
		lineageTag: 0f88ca66-5fad-4522-84ec-8f9e00b53b75

	measure page_header_name_5_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: e4461850-ff0f-4de9-9fc2-bd68ae6a0184

	measure page_header_name_5_2_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_header_name
		lineageTag: ed689f79-6835-4e2a-ae0c-7d656bc5775f

	measure page_header_name_5_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 44f22adc-be2a-4a37-924e-3dc91b2772cd

	measure page_header_name_5_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 23f7f379-7079-4949-a186-1982d8299641

	measure page_header_name_5_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 710a7dd1-43bf-4078-94e7-3175fcf3a0d9

	measure page_header_name_5_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 5,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 10f61499-9b21-40dc-aac4-67d5ffc9ff0f

	measure page_header_name_6_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 761da282-0398-4c92-8578-22c6caa9d414

	measure page_header_name_6_1_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_header_name
		lineageTag: 05ebd222-1825-46f1-8057-f5b44266eec0

	measure page_header_name_6_1_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_header_name
		lineageTag: 94ffdbe2-6551-492b-bb76-8828da7a2e34

	measure page_header_name_6_1_4 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_header_name
		lineageTag: e634fe9a-f052-481e-b358-d89146ca0a63

	measure page_header_name_6_1_5 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_header_name
		lineageTag: 16873a5b-d979-4a67-ad9d-5b5cee8ac4fb

	measure page_header_name_6_1_6 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: page_header_name
		lineageTag: 7b89fbdb-a824-49c5-a7e4-e45786469730

	measure page_header_name_6_1_7 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 7
			)
		displayFolder: page_header_name
		lineageTag: 6bd53ad0-cba5-4198-8d43-36c67f9aa166

	measure page_header_name_6_1_8 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 8
			)
		displayFolder: page_header_name
		lineageTag: d267efbb-ef76-4bd9-b5e9-9180a7701e43

	measure page_header_name_6_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 4f8ffcd4-6b5f-458a-99aa-7ac9fb611188

	measure page_header_name_6_2_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_header_name
		lineageTag: 21dd5eb7-a2c4-40ea-afac-e70f0c537e56

	measure page_header_name_6_2_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_header_name
		lineageTag: b9c6df0a-4913-425c-8861-3c1573134e91

	measure page_header_name_6_2_4 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_header_name
		lineageTag: 54e0ad72-f73c-47ef-8b17-3e18c12d6540

	measure page_header_name_6_2_5 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_header_name
		lineageTag: c8c035ea-27c2-407a-998a-b83209ac13f1

	measure page_header_name_6_2_6 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: page_header_name
		lineageTag: a99db503-68db-48b2-bfae-b2d510774a9c

	measure page_header_name_6_2_7 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 7
			)
		displayFolder: page_header_name
		lineageTag: 77e492bf-6e19-4084-a2ab-968d958e1d81

	measure page_header_name_6_2_8 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 8
			)
		displayFolder: page_header_name
		lineageTag: a0e65d57-d3ef-4c83-aa97-f2c8de5dee7d

	measure page_header_name_6_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 6da24efd-5891-402b-8e1f-69ce109199d8

	measure page_header_name_6_3_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_header_name
		lineageTag: 505f6979-9d43-4423-adac-e08a3f1c4a1c

	measure page_header_name_6_3_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_header_name
		lineageTag: d43df508-4c82-4c3a-87b8-8e63dc37d1f5

	measure page_header_name_6_3_4 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_header_name
		lineageTag: b0dde9d3-8910-4f41-8fa1-a6314c3fdf52

	measure page_header_name_6_3_5 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_header_name
		lineageTag: b842c05a-8a27-4d09-aa74-bed9245deb24

	measure page_header_name_6_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 62b0dfb4-bd7c-4a04-96e5-7ec90e0e5328

	measure page_header_name_6_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: e355318a-214f-4c18-8ec3-ff02b37ff46a

	measure page_header_name_6_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 6,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: e52aab16-9025-41a4-bcae-3d7d57861b50

	measure page_header_name_7_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: dfd07d90-4ebf-46b1-ac4a-4bc55d893214

	measure page_header_name_7_1_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_header_name
		lineageTag: 9dada6d6-5fc9-4c76-8e64-7f0866d751ac

	measure page_header_name_7_1_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_header_name
		lineageTag: 5222fdd9-d356-4eeb-8b4e-ae3b121c61c4

	measure page_header_name_7_1_4 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_header_name
		lineageTag: f9fb0205-1535-470c-b7ab-18afeb747262

	measure page_header_name_7_1_5 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_header_name
		lineageTag: d9a1bf4b-4d91-4950-b6b7-c63c0a35b0f8

	measure page_header_name_7_1_6 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: page_header_name
		lineageTag: 387579c8-5de4-44a4-bd70-9845bed08d6a

	measure page_header_name_7_1_7 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 7
			)
		displayFolder: page_header_name
		lineageTag: 99e33574-4dba-4057-997c-794b41386f0d

	measure page_header_name_7_1_8 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 8
			)
		displayFolder: page_header_name
		lineageTag: 38776d26-bc83-4766-890b-4f1a140d7f45

	measure page_header_name_7_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 56058b75-1ba2-4407-8d3a-9e4589c1699d

	measure page_header_name_7_2_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_header_name
		lineageTag: 25591fa8-d6c5-467d-a131-d23e90a1b40c

	measure page_header_name_7_2_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_header_name
		lineageTag: b1012c35-414d-4388-bfc9-045a37a8d038

	measure page_header_name_7_2_4 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_header_name
		lineageTag: 0bda283c-da91-48ee-be3f-44bb2ca8749e

	measure page_header_name_7_2_5 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_header_name
		lineageTag: 331004b4-43bd-4f1b-a5b9-17b82b13d316

	measure page_header_name_7_2_6 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: page_header_name
		lineageTag: 20e09d8e-a185-4f9c-81de-3e704312771f

	measure page_header_name_7_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 7d673558-151c-41b9-8fb7-319be0f3103e

	measure page_header_name_7_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: fae2ff4c-c81b-4489-a788-81e8ae193453

	measure page_header_name_7_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 10fcb729-a8ca-49ef-97bc-851033b08b6d

	measure page_header_name_7_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 7,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 299b922c-ff13-4dd6-9654-883c4f8650c3

	measure page_header_name_8_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 372ccdde-ef99-4093-8e17-f0979ee24063

	measure page_header_name_8_1_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_header_name
		lineageTag: cce1cefc-0f46-4b6a-ac6f-6f46226df72f

	measure page_header_name_8_1_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_header_name
		lineageTag: f4d45431-972b-4d23-9a4f-385eeee2d418

	measure page_header_name_8_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 81ae31f0-7ab5-4ded-be49-b28cd64ca298

	measure page_header_name_8_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: a2ce88b5-7b12-48d2-b288-fd9034298af4

	measure page_header_name_8_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: f0d15f42-1b29-40fb-8564-e8bb0f57e23b

	measure page_header_name_8_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: b991746b-3757-4af6-ab7a-b0faa0add3b6

	measure page_header_name_8_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: e002b57e-ce2e-46bc-8c80-2bc3a74d05ad

	measure page_header_name_8_7_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 24f46dd1-615a-4269-85b5-ffd5948b3b0c

	measure page_header_name_8_8_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 64bebe9f-37ac-4373-90f2-393dc65b718e

	measure page_header_name_8_9_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 8,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 1eb42105-d2c6-43f9-8e50-3c6c33a8b359

	measure page_header_name_9_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: f29471b9-6225-4e2d-b312-e5f4cc558eef

	measure page_header_name_9_1_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_header_name
		lineageTag: b32f2ff1-e62f-4453-b891-27c6bd72f904

	measure page_header_name_9_1_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_header_name
		lineageTag: e1ee8b34-d810-49fb-a7ba-507e2c0c2734

	measure page_header_name_9_1_4 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_header_name
		lineageTag: 2c9f1185-ff80-47d4-b542-90845c33c6a0

	measure page_header_name_9_1_5 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_header_name
		lineageTag: 20840662-b2b2-42e4-af77-9a346a94f1e0

	measure page_header_name_9_1_6 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 6
			)
		displayFolder: page_header_name
		lineageTag: 6e9c4466-be8c-48d9-8e5c-a2dfc5fe0a8e

	measure page_header_name_9_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: aefc643d-67ee-403e-bf5d-fd9c92c1b71a

	measure page_header_name_9_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 3f9e9dc0-a290-4d15-8f7d-e4f7a39e028a

	measure page_header_name_9_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 5fd3b6de-30b1-4b2d-8af2-2a10bde25a0e

	measure page_header_name_9_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 4af90da0-6366-40d2-b95a-512c492435a1

	measure page_header_name_9_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: a05914ea-b468-4175-b1e9-c7ba69610bc0

	measure page_header_name_10_7_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: f66a6b40-fa0f-4d88-af88-105575b37ef4

	measure page_header_name_10_8_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: e145925a-0e07-499e-b046-a9f108c78a83

	measure page_header_name_10_9_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: d0ea3c22-a39f-4eda-a0cf-830955588bc4

	measure page_header_name_12_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 12,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 99e88dad-8087-4515-a95d-81988640d84f

	measure page_header_name_9_7_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: ba7b69ae-8566-4096-b0bf-0b07b798d3b7

	measure page_header_name_9_8_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 803910e0-cadb-4521-8567-4bce404f7ff1

	measure page_header_name_9_9_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 9,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 864bd131-69bd-48a0-9c02-f54daa8ad679

	measure page_header_name_13_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 08791a5e-72b7-402e-b980-02233aa6d65f

	measure page_header_name_15_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: d27e33d5-80c3-4771-813f-26606cf18d90

	measure page_header_name_14_1_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 16a8cd1a-2535-44af-98bc-95e5d1426ffa

	measure page_header_name_13_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 2c134154-7b8e-404e-bd13-e6bafebb39fe

	measure page_header_name_14_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 53bf659b-9b93-4703-9fb1-b125889b0fd5

	measure page_header_name_15_2_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: dbbdb0ee-826b-406a-b772-de6a0138def5

	measure page_header_name_13_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 3692ae39-d172-4cbc-8759-1cbc787c356d

	measure page_header_name_14_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 26991ef7-964e-4449-91da-a952a8ea6003

	measure page_header_name_15_3_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: df91aca2-a79a-4297-8c03-c7fd56d3596b

	measure page_header_name_13_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 5b970dce-16ea-448e-84cb-a89c1e1297f6

	measure page_header_name_14_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: d45daa11-de97-433d-843c-64c353767d70

	measure page_header_name_15_4_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: dc092cfe-5c2f-4aeb-867d-369cc01f3bdc

	measure page_header_name_13_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 83fa59c8-b7ea-4093-b826-6b7b0f073007

	measure page_header_name_14_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 0b6211b8-f4af-45b9-9072-58a856acf87a

	measure page_header_name_15_5_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 9d98e979-6f1e-488f-8a65-2bd3b3a7aede

	measure page_header_name_13_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 6f2a4bdc-501a-4fe7-a1fa-2eb9d0660978

	measure page_header_name_14_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 931cf4e8-46be-4410-8eab-685fdf44ceef

	measure page_header_name_15_6_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 6,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: cdfe658f-4a5a-4e52-80df-eb88d8b31b5b

	measure page_header_name_13_7_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: f66585de-0ab3-4dc1-8de6-81351ebb798e

	measure page_header_name_14_7_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 6e3bc209-9279-4a8e-87c3-9f72114a732c

	measure page_header_name_15_7_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 7,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: dcc21245-660f-4b5d-bafa-5545b250ed42

	measure page_header_name_13_8_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 5d8f3b0f-1a1c-4ae1-94cd-336782cbf57d

	measure page_header_name_14_8_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: d220fd00-5f49-4f64-b12e-4e7029b05295

	measure page_header_name_15_8_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 8,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 71aee672-ffc7-484c-8b13-bad625d87836

	measure page_header_name_13_9_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 13,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 16cf9717-56ad-49f1-bfcc-9ca552313977

	measure page_header_name_14_9_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 14,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: c7e49fe9-93c0-447d-ac7f-d2dd443d7696

	measure page_header_name_15_9_1 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard] ) & " - " & MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 9,
			    'dashboards_url'[id_page] = 1
			)
		displayFolder: page_header_name
		lineageTag: 0b606548-0956-4af4-8edd-f522e099b95f

	measure page_header_name_10_4_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard]) & " - " & MAX ( 'dashboards_url'[name_page]),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_header_name
		lineageTag: 0dabd986-db61-41c2-acbc-a406760e266c

	measure page_header_name_15_4_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_dashboard]) & " - " & MAX ( 'dashboards_url'[name_page]),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_header_name
		lineageTag: 99225973-d9a1-4f34-bd50-2459f15516c6

	measure dash_url_15_3_2 =
			CALCULATE (
			    IF ( [CountRows_15_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_url
		lineageTag: c13fd8e9-c29d-486a-abea-3efd8b44f577

	measure dash_url_15_3_3 =
			CALCULATE (
			    IF ( [CountRows_15_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_url
		lineageTag: fa753dc4-143d-4281-89ec-89b007968ff3

	measure dash_url_15_3_4 =
			CALCULATE (
			    IF ( [CountRows_15_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_url
		lineageTag: e4a52dbd-26f1-401d-94da-bf37946c8b39

	measure dash_url_15_3_5 =
			CALCULATE (
			    IF ( [CountRows_15_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_url
		lineageTag: ca57bdb5-ce04-4d2c-b859-bcd0afc98e30

	measure page_name_15_1_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: 20d46d9a-8872-45e7-aa40-130f6e946197

	measure page_name_15_4_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: 20b280d8-5b0d-4bf0-b59c-e37137769104

	measure page_name_15_3_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: 0501fb15-d48b-4694-92b9-bbf87e8ff06c

	measure page_name_15_3_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_name
		lineageTag: 90e8e48b-ca22-4441-b43c-ab2019315854

	measure page_name_15_3_4 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 4
			)
		displayFolder: page_name
		lineageTag: 013f1cb1-cd53-41d4-b868-857a571498a2

	measure page_name_15_3_5 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 3,
			    'dashboards_url'[id_page] = 5
			)
		displayFolder: page_name
		lineageTag: b1dc9137-1d99-496b-9dd6-68101889f07e

	measure dash_url_15_1_2 =
			CALCULATE (
			    IF ( [CountRows_15_1] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_url
		lineageTag: e44d22de-7255-4e8a-b148-7e10e825f0eb

	measure dash_url_15_4_2 =
			CALCULATE (
			    IF ( [CountRows_15_3] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_url
		lineageTag: 222b2ada-890b-4de1-9c96-d8b0d301285c

	measure page_name_15_5_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 2
			)
		lineageTag: 8241c1ed-2126-4531-8b65-b852a8127364

	measure dash_url_15_5_2 =
			CALCULATE (
			    IF ( [CountRows_15_5] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 2
			)
		lineageTag: f7f18958-bdb6-4e15-9598-55bcbd1d7517

	measure page_name_10_1_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 1,
			    'dashboards_url'[id_page] = 2
			)
		lineageTag: 7d5492f0-cffd-4f00-a139-e5f8766aa9c4

	measure page_name_10_4_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 2
			)
		lineageTag: 25d2ea32-94ca-44a2-8e3e-c9c54219e385

	measure page_name_15_5_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_name
		lineageTag: 705dd59a-a5a7-4879-8e3f-19af98a9d374

	measure dash_url_15_5_3 =
			CALCULATE (
			    IF ( [CountRows_15_5] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 15,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_url
		lineageTag: 357d0d16-b0e5-47a5-8d25-0022562712f5

	measure page_name_10_5_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: aaa6a5eb-84fc-4cd6-a4d7-6af81203bc34

	measure dash_url_10_5_2 =
			CALCULATE (
			    IF ( [CountRows_10_5] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_url
		lineageTag: 93f5c462-2145-4e5c-b068-10870ce732d9

	measure dash_url_10_5_3 =
			CALCULATE (
			    IF ( [CountRows_10_5] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_url
		lineageTag: 23fdee6d-6f1f-4a0b-99d8-63c8c9cc867f

	measure page_name_10_5_3 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 5,
			    'dashboards_url'[id_page] = 3
			)
		displayFolder: page_name
		lineageTag: 0219faec-0694-43de-86ae-2e521149d049

	measure CountRows_16_4 =
			IF (
			    CALCULATE (
			        COUNTROWS ( 'dim_access_control' ),
			        'dim_access_control'[id_vertical] = 16,
			        'dim_access_control'[id_dashboard] = 4) >= 1, 1,
			    0
			)
		formatString: 0
		lineageTag: fb5b876c-8c70-4fc1-b72a-3082c722334b

	measure dash_url_16_4_1 =
			CALCULATE (
			    IF ( [CountRows_16_4] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 16,
			    'dashboards_url'[id_dashboard] = 4,
			    'dashboards_url'[id_page] = 1
			)
		lineageTag: f279b7fa-eb15-4da5-a658-63fb6e49de8e

	measure dash_name_10_2_2 =
			CALCULATE (
			    IF ( [CountRows_url_10_2] = 1, MAX ( 'dashboards_url'[name_dashboard] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: afc478ab-17ab-4fe7-b9ce-90b6012a351b

	measure page_name_10_2_2 =
			CALCULATE (
			    MAX ( 'dashboards_url'[name_page] ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_name
		lineageTag: 6ab94bec-d99f-44d9-b97c-772dd4f91ec8

	measure dash_url_10_2_2 =
			CALCULATE (
			    IF ( [CountRows_10_2] = 1, MAX ( 'dashboards_url'[url] ), "" ),
			    'dashboards_url'[id_vertical] = 10,
			    'dashboards_url'[id_dashboard] = 2,
			    'dashboards_url'[id_page] = 2
			)
		displayFolder: page_url
		lineageTag: 832d1bda-9048-4211-b9ed-80ff94840f8c

	column 'Coluna 1'
		dataType: string
		isHidden
		lineageTag: f32468d0-8d76-4d14-9b03-d3d0b11a21a4
		summarizeBy: none
		sourceColumn: Coluna 1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Medidas Produto-cb3aec2a-098b-4434-946d-2906370e958b' = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

