table 'Ultima Atualizacao'
	lineageTag: f1686255-4a4f-4bdc-8572-57d93340c477

	measure max_ultima_data = MAX('Ultima Atualizacao'[Ultima Atualizacao])
		formatString: General Date
		lineageTag: 2acbf81c-b2c2-49a8-b407-0ebfc89379a2

	column 'Ultima Atualizacao'
		dataType: dateTime
		formatString: General Date
		lineageTag: 812320fd-606b-4dcd-94cf-d7bc6a46dc38
		summarizeBy: none
		sourceColumn: Ultima Atualizacao

		annotation SummarizationSetBy = Automatic

	partition 'Ultima Atualizacao-8f84ee21-1c50-44db-b81c-cf76722fe226' = m
		mode: import
		source =
				let
				    Fonte = DateTimeZone.SwitchZone(DateTimeZone.FixedLocalNow(),-3,0)
				in
				    Fonte

	annotation PBI_ResultType = DateTimeZone

